# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: Averb_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteAverb_v100 import *


class evento(TEvento):
    """Schema XML de validação do evento de Averbação da NFe"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


