# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: CCe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteCCe_v100 import *


class evento(TEvento):
    """Schema XML de validação do evento Carta de Correção"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


