# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: confRecebto_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConfRecebto_v100 import *


class evento(TEvento):
    """Schema XML de validação do evento Confirmação de recebimento"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


