# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consStatServ_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsStatServ_v310 import *


class consStatServ(TConsStatServ):
    """Schema XML de validação do Pedido de Consulta do Status do Serviço"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


