# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consNFeDest_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsNFeDest_v101 import *


class consNFeDest(TConsNFeDest):
    """Schema de validação XML dp Pedido de Consulta de NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


