# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consReciNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteNFe_v310 import *


class consReciNFe(TConsReciNFe):
    """Schema XML de validação do Pedido de Consulta do Recido do Lote de Notas Fiscais Eletrônicas"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


