# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consSitNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsSitNFe_v310 import *


class consSitNFe(TConsSitNFe):
    """Schema de validação XML dp Pedido de Consulta da Situação Atual da Nota Fiscal Eletrônica"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


