# Generated by xsd2py.py
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteConsNFeDest_v101 import *


class consNFeDest(TConsNFeDest):
    """Schema de validação XML dp Pedido de Consulta de NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

