# Generated by xsd2py.py
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteConsStatServ_v310 import *


class consStatServ(TConsStatServ):
    """Schema XML de validação do Pedido de Consulta do Status do Serviço"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

