# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consReciNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteNFe_v310 import *


class consReciNFe(TConsReciNFe):
    """Schema XML de validação do Pedido de Consulta do Recido do Lote de Notas Fiscais Eletrônicas"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


