# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: downloadNFe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteDownloadNFe_v100 import *


class downloadNFe(TDownloadNFe):
    """Schema de validação XML dp Pedido de download de NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


