# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: e110111_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .tiposBasico_v103 import *


class detEvento(ComplexType):
    """Schema XML de validação do evento do cancelamento 1101111"""
    versao: Annotated[str, Attribute(enumeration=['1.00'])] = None
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    xJust: Annotated[TJust, Element] = None


