# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: e110110_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import Annotated

from brasil.dfe.xsd import ComplexType, Attribute, Element


class detEvento(ComplexType):
    """Schema XML de validação do evento do carta de correção e1101110"""
    versao: Annotated[str, Attribute(enumeration=['1.00'])] = None
    descEvento: Annotated[str, Element] = None
    xCorrecao: Annotated[str, Element] = None
    xCondUso: Annotated[str, Element] = None


