# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: e790700_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposBasico_v103 import *


class detEvento(ComplexType):
    """Schema XML de validação do evento de averbação da NFe (e790700)"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"
    versao: Annotated[str, Attribute(enumeration=['1.00'])] = None
    descEvento: Annotated[str, Element] = None
    tpAutor: Annotated[str, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None

    class _itensAverbados(ComplexType):
        """Informações dos itens da NF-e do evento."""
        dhEmbarque: Annotated[datetime | str, Element] = None
        dhAverbacao: Annotated[datetime | str, Element] = None
        nDue: Annotated[str, Element] = None
        nItem: Annotated[str, Element] = None
        nItemDue: Annotated[str, Element] = None
        qItem: Annotated[TDec_1104Neg, Element] = None
        motAlteracao: Annotated[str, Element] = None

    itensAverbados: Annotated[ElementList[_itensAverbados], Element] = None


