# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: e990900_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .tiposBasico_v103 import *


class detEvento(ComplexType):
    """Schema XML de validação do evento doVistoria SUFRAMA 990900"""
    versao: Annotated[str, Attribute(enumeration=['1.00'])] = None
    descEvento: Annotated[str, Element] = None
    PINe: Annotated[str, Element] = None
    dVistoria: Annotated[str, Element] = None
    locVistoria: Annotated[str, Element] = None
    postoVistoria: Annotated[str, Element] = None
    xHistorico: Annotated[str, Element] = None


