# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: envCCe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteCCe_v100 import *


class envEvento(TEnvEvento):
    """Schema XML de validação do lote de envio do evento carta de correção"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


