# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: envCancelPProrrogNFe_v1.0.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .tiposBasico_v310 import *


class detEvento(ComplexType):
    """Informações do Cancelamento de Pedido de Prorrogação"""
    versao: Annotated[str, Attribute(enumeration=['1.00'])] = None
    descEvento: Annotated[str, Element] = None
    idPedidoCancelado: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None


