# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: envEventoCancSubst_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEventoCancSubst_v100 import *


class envEvento(TEnvEvento):
    """Schema XML de validação do lote de envio do evento cancelamento"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


