# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: envEvento_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEvento_v100 import *


class envEvento(TEnvEvento):
    """Schema XML de validação do lote de envio do Evento"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


