# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: envEPEC_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEPEC_v100 import *


class envEvento(TEnvEvento):
    """Schema XML de validação do lote de envio do Evento Prévio de Emissão em Contingência"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


