# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: envRemIndus_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteRemIndus_v100 import *


class envEvento(TEnvEvento):
    """Schema XML de validacao do pedido de prorrogacao de remessa para industrializacao"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


