# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: EPEC_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEPEC_v100 import *


class evento(TEvento):
    """Schema XML de validação do Evento Prévio de Emissão em Contingência"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


