# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: eventoAtorInteressado_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEventoAtorInteressado_v100 import *


class evento(TEvento):
    """Schema XML de validação do evento de Ator Interessado na NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


