# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: eventoRemIndus_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteRemIndus_v100 import *


class evento(TEvento):
    """Schema XML de validação do evento Remessa para Industrializacao"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


