# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: inutNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteInutNFe_v310 import *


class inutNFe(TInutNFe):
    """Schema XML de validação do Pedido de Inutilização de Numeração da Nota Fiscal Eletrônica"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


