# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: leiauteConsSitNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposBasico_v400 import *


TVerConsSitNFe: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do Leiaute da Cosulta situação NF-e - 4.00""", ]


class TConsSitNFe(ComplexType):
    """Tipo Pedido de Consulta da Situação Atual da Nota Fiscal Eletrônica"""
    versao: Annotated[TVerConsSitNFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    xServ: Annotated[TServ, Element] = None
    chNFe: Annotated[TChNFe, Element] = None


TVerNFe: TypeAlias = Annotated[str, SimpleType, """ Tipo Versão da NF-e""", ]


class TProtNFe(ComplexType):
    """Tipo Protocolo de status resultado do processamento da NF-e"""
    versao: Annotated[TVerNFe, Attribute] = None

    class _infProt(ComplexType):
        """Dados do protocolo de status"""
        Id: Annotated[str, Attribute] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        chNFe: Annotated[TChNFe, Element] = None
        dhRecbto: Annotated[datetime | str, Element] = None
        nProt: Annotated[TProt, Element] = None
        digVal: Annotated[TXML, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None

    infProt: Annotated[_infProt, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


TVerCancNFe: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do leiaute de Cancelamento de NF-e - 2.00/1.07""", ]


class TRetCancNFe(ComplexType):
    """Tipo retorno Pedido de Cancelamento da Nota Fiscal Eletrônica"""
    versao: Annotated[TVerCancNFe, Attribute] = None

    class _infCanc(ComplexType):
        """Dados do Resultado do Pedido de Cancelamento da Nota Fiscal Eletrônica"""
        Id: Annotated[str, Attribute] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None
        cUF: Annotated[TCodUfIBGE, Element] = None
        chNFe: Annotated[TChNFe, Element] = None
        dhRecbto: Annotated[datetime | str, Element] = None
        nProt: Annotated[TProt, Element] = None

    infCanc: Annotated[_infCanc, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


TRetVerEvento: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do Evento""", ]


class TRetEvento(ComplexType):
    """Tipo retorno do Evento"""
    versao: Annotated[TRetVerEvento, Attribute] = None

    class _infEvento(ComplexType):
        Id: Annotated[str, Attribute(pattern=r'ID[0-9]{15}')] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        cOrgao: Annotated[TCOrgaoIBGE, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None
        chNFe: Annotated[TChNFe, Element] = None
        tpEvento: Annotated[str, Element] = None
        xEvento: Annotated[str, Element] = None
        nSeqEvento: Annotated[str, Element] = None
        CNPJDest: Annotated[TCnpjOpc, Element] = None
        CPFDest: Annotated[TCpf, Element] = None
        CNPJDest_CPFDest = Choice("CNPJDest", "CPFDest")
        emailDest: Annotated[str, Element] = None
        dhRegEvento: Annotated[datetime | str, Element] = None
        nProt: Annotated[TProt, Element] = None

    infEvento: Annotated[_infEvento, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


TVerEvento: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do Evento 1.00""", ]


class TEvento(ComplexType):
    """Tipo Evento"""
    versao: Annotated[TVerEvento, Attribute] = None

    class _infEvento(ComplexType):
        Id: Annotated[str, Attribute(pattern=r'ID[0-9]{52}')] = None
        cOrgao: Annotated[TCOrgaoIBGE, Element] = None
        tpAmb: Annotated[TAmb, Element] = None
        CNPJ: Annotated[TCnpjOpc, Element] = None
        CPF: Annotated[TCpf, Element] = None
        CNPJ_CPF = Choice("CNPJ", "CPF")
        chNFe: Annotated[TChNFe, Element] = None
        dhEvento: Annotated[datetime | str, Element] = None
        tpEvento: Annotated[str, Element] = None
        nSeqEvento: Annotated[str, Element] = None
        verEvento: Annotated[str, Element] = None

        class _detEvento(ComplexType):
            """Detalhe Específico do Evento"""

        detEvento: Annotated[_detEvento, Element] = None

    infEvento: Annotated[_infEvento, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TProcEvento(ComplexType):
    """Tipo procEvento"""
    versao: Annotated[TVerEvento, Attribute] = None
    evento: Annotated[TEvento, Element] = None
    retEvento: Annotated[TRetEvento, Element] = None


class TRetConsSitNFe(ComplexType):
    """Tipo Retorno de Pedido de Consulta da Situação Atual da Nota Fiscal Eletrônica """
    versao: Annotated[TVerConsSitNFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    dhRecbto: Annotated[datetime | str, Element] = None
    chNFe: Annotated[TChNFe, Element] = None
    protNFe: Annotated[TProtNFe, Element] = None
    retCancNFe: Annotated[TRetCancNFe, Element] = None
    procEventoNFe: Annotated[ElementList[TProcEvento], Element] = None


