# Generated by xsd2py.py
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposBasico_v103 import *


class TVerEvento(str):
    """Tipo Versão do Evento"""
    pass


class TCOrgaoIBGE(str):
    """Tipo Código de orgão (UF da tabela do IBGE + 90 RFB)"""
    pass


class TEvento(ComplexType):
    """Tipo Evento"""
    versao: Annotated[TVerEvento, Attribute] = None

    class _infEvento(ComplexType):
        Id: Annotated[str, Attribute(pattern='ID[0-9]{52}')] = None
        cOrgao: Annotated[TCOrgaoIBGE, Element] = None
        tpAmb: Annotated[TAmb, Element] = None
        CNPJ: Annotated[TCnpjOpc, Element] = None
        CPF: Annotated[TCpf, Element] = None
        CNPJ_CPF = Choice("CNPJ", "CPF")
        chNFe: Annotated[TChNFe, Element] = None
        dhEvento: Annotated[TDateTimeUTC, Element] = None
        tpEvento: Annotated[str, Element] = None
        nSeqEvento: Annotated[str, Element] = None
        verEvento: Annotated[str, Element] = None

        class _detEvento(ComplexType):
            """Schema XML de validação do evento doVistoria SUFRAMA 990900"""
            versao: Annotated[str, Attribute(enumeration=['1.00'])] = None
            descEvento: Annotated[str, Element] = None
            PINe: Annotated[str, Element] = None
            dVistoria: Annotated[str, Element] = None
            locVistoria: Annotated[str, Element] = None
            postoVistoria: Annotated[str, Element] = None
            xHistorico: Annotated[str, Element] = None

        detEvento: Annotated[_detEvento, Element] = None

    infEvento: Annotated[_infEvento, Element] = None
    Signature: Annotated[XmlSignature, Element] = None

descEvento: Annotated[str, Element] = None

class cOrgaoAutor(TCOrgaoIBGE):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

cPostoUF: Annotated[str, Element] = None
xPostoUF: Annotated[str, Element] = None
latGPS: Annotated[str, Element] = None
longGPS: Annotated[str, Element] = None

class CPFOper(TCpf):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

xNomeOper: Annotated[str, Element] = None
indOffline: Annotated[str, Element] = None

class dhPas(TDateTimeUTC):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

sentidoVia: Annotated[str, Element] = None
indRet: Annotated[str, Element] = None

class UFDest(TUf):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

xObs: Annotated[str, Element] = None
chMDFe: Annotated[str, Element] = None
chCTe: Annotated[str, Element] = None

class modalRodov(ComplexType):
    placaVeic: Annotated[str, Element] = None
    UFVeic: Annotated[str, Element] = None
    placaCarreta: Annotated[str, Element] = None
    UFCarreta: Annotated[str, Element] = None
    placaCarreta2: Annotated[str, Element] = None
    UFCarreta2: Annotated[str, Element] = None


class placaVeic(TPlaca):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class UFVeic(TUf):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class placaCarreta(TPlaca):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class UFCarreta(TUf):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class placaCarreta2(TPlaca):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class UFCarreta2(TUf):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class modalOutro(ComplexType):
    tpModal: Annotated[str, Element] = None
    xIdent: Annotated[str, Element] = None

tpModal: Annotated[str, Element] = None
xIdent: Annotated[str, Element] = None

class ctg(ComplexType):
    nFormSeg: Annotated[str, Element] = None
    UFDest: Annotated[str, Element] = None
    tpEmis: Annotated[str, Element] = None
    CNPJDest: Annotated[str, Element] = None
    CPFDest: Annotated[str, Element] = None
    CNPJDest_CPFDest = Choice("CNPJDest", "CPFDest")
    vTotalNFe: Annotated[str, Element] = None
    indICMS: Annotated[str, Element] = None
    indICMSST: Annotated[str, Element] = None
    diaEmi: Annotated[str, Element] = None

nFormSeg: Annotated[str, Element] = None
tpEmis: Annotated[str, Element] = None

class CNPJDest(TCnpj):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class CPFDest(TCpf):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


class vTotalNFe(TDec_1302):
    _xmlns = "http://www.portalfiscal.inf.br/nfe"

indICMS: Annotated[str, Element] = None
indICMSST: Annotated[str, Element] = None
diaEmi: Annotated[str, Element] = None

class TretEvento(ComplexType):
    """Tipo retorno do Evento"""
    versao: Annotated[TVerEvento, Attribute] = None

    class _infEvento(ComplexType):
        Id: Annotated[str, Attribute(pattern='ID[0-9]{15}')] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        cOrgao: Annotated[TCOrgaoIBGE, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None
        chNFe: Annotated[TChNFe, Element] = None
        tpEvento: Annotated[str, Element] = None
        xEvento: Annotated[str, Element] = None
        nSeqEvento: Annotated[str, Element] = None
        CNPJDest: Annotated[TCnpjOpc, Element] = None
        CPFDest: Annotated[TCpf, Element] = None
        CNPJDest_CPFDest = Choice("CNPJDest", "CPFDest")
        emailDest: Annotated[str, Element] = None
        dhRegEvento: Annotated[str, Element] = None
        nProt: Annotated[TProt, Element] = None

    infEvento: Annotated[_infEvento, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TVerEnvEvento(str):
    """Tipo Versão do EnvEvento"""
    pass


class TEnvEvento(ComplexType):
    """ Tipo Lote de Envio"""
    versao: Annotated[TVerEnvEvento, Attribute] = None
    idLote: Annotated[str, Element] = None
    evento: Annotated[List[TEvento], Element] = None


class TRetEnvEvento(ComplexType):
    """ Tipo Retorno de Lote de Envio"""
    versao: Annotated[TVerEnvEvento, Attribute] = None
    idLote: Annotated[str, Element] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cOrgao: Annotated[TCOrgaoIBGE, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    retEvento: Annotated[List[TretEvento], Element] = None


class TProcEvento(ComplexType):
    """Tipo procEvento"""
    versao: Annotated[TVerEvento, Attribute] = None
    evento: Annotated[TEvento, Element] = None
    retEvento: Annotated[TretEvento, Element] = None

