# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: leiauteConsNFeDest_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposBasico_v103 import *


class TNSU(str):
    """ Tipo número sequencial único do AN"""
    pass


class TVeConsNFeDest(str):
    """ Tipo Versão da consultaNFeDest"""
    pass


class TConsNFeDest(ComplexType):
    """Tipo Pedido de Consulta de Nota Fiscal Eletrônica"""
    versao: Annotated[TVeConsNFeDest, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    xServ: Annotated[str, Element] = None
    CNPJ: Annotated[TCnpj, Element] = None
    indNFe: Annotated[str, Element] = None
    indEmi: Annotated[str, Element] = None
    ultNSU: Annotated[str, Element] = None


class TRetConsNFeDest(ComplexType):
    """Tipo Retorno do pedido de Consulta de Nota Fiscal Eletrônica"""
    versao: Annotated[TVeConsNFeDest, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    dhResp: Annotated[datetime, Element] = None
    indCont: Annotated[str, Element] = None
    ultNSU: Annotated[str, Element] = None

    class _ret(ComplexType):
        """Resumo de NF-e ou CC-e"""

        class _resNFe(ComplexType):
            """Informações resumo da NF-e localizadas"""
            NSU: Annotated[TNSU, Attribute] = None
            chNFe: Annotated[TChNFe, Element] = None
            CNPJ: Annotated[TCnpj, Element] = None
            CPF: Annotated[TCpf, Element] = None
            CNPJ_CPF = Choice("CNPJ", "CPF")
            xNome: Annotated[str, Element] = None
            IE: Annotated[TIe, Element] = None
            dEmi: Annotated[TData, Element] = None
            tpNF: Annotated[str, Element] = None
            vNF: Annotated[TDec_1302, Element] = None
            digVal: Annotated[str, Element] = None
            dhRecbto: Annotated[datetime, Element] = None
            cSitNFe: Annotated[str, Element] = None
            cSitConf: Annotated[str, Element] = None

        resNFe: Annotated[_resNFe, Element] = None

        class _resCanc(ComplexType):
            """Informações resumo da NF-e canceladas localizadas"""
            NSU: Annotated[TNSU, Attribute] = None
            chNFe: Annotated[TChNFe, Element] = None
            CNPJ: Annotated[TCnpj, Element] = None
            CPF: Annotated[TCpf, Element] = None
            CNPJ_CPF = Choice("CNPJ", "CPF")
            xNome: Annotated[str, Element] = None
            IE: Annotated[TIe, Element] = None
            dEmi: Annotated[TData, Element] = None
            tpNF: Annotated[str, Element] = None
            vNF: Annotated[TDec_1302, Element] = None
            digVal: Annotated[str, Element] = None
            dhRecbto: Annotated[datetime, Element] = None
            cSitNFe: Annotated[str, Element] = None
            cSitConf: Annotated[str, Element] = None

        resCanc: Annotated[_resCanc, Element] = None

        class _resCCe(ComplexType):
            """Informações da carta de correção da NF-e localizadas"""
            NSU: Annotated[TNSU, Attribute] = None
            chNFe: Annotated[TChNFe, Element] = None
            dhEvento: Annotated[str, Element] = None
            tpEvento: Annotated[str, Element] = None
            nSeqEvento: Annotated[str, Element] = None
            descEvento: Annotated[str, Element] = None
            xCorrecao: Annotated[str, Element] = None
            tpNF: Annotated[str, Element] = None
            dhRecbto: Annotated[datetime, Element] = None

        resCCe: Annotated[_resCCe, Element] = None
        resNFe_resCanc_resCCe = Choice("resNFe", "resCanc", "resCCe")

    ret: Annotated[ElementList[_ret], Element] = None


