# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: leiauteNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposBasico_v400 import *


class TEndereco(ComplexType):
    """Tipo Dados do Endereço  // 24/10/08 - tamanho mínimo"""
    xLgr: Annotated[str, Element] = None
    nro: Annotated[str, Element] = None
    xCpl: Annotated[str, Element] = None
    xBairro: Annotated[str, Element] = None
    cMun: Annotated[TCodMunIBGE, Element] = None
    xMun: Annotated[str, Element] = None
    UF: Annotated[TUf, Element] = None
    CEP: Annotated[str, Element] = None
    cPais: Annotated[str, Element] = None
    xPais: Annotated[str, Element] = None
    fone: Annotated[str, Element] = None


class TEnderEmi(ComplexType):
    """Tipo Dados do Endereço do Emitente  // 24/10/08 - desmembrado / tamanho mínimo"""
    xLgr: Annotated[str, Element] = None
    nro: Annotated[str, Element] = None
    xCpl: Annotated[str, Element] = None
    xBairro: Annotated[str, Element] = None
    cMun: Annotated[TCodMunIBGE, Element] = None
    xMun: Annotated[str, Element] = None
    UF: Annotated[TUfEmi, Element] = None
    CEP: Annotated[str, Element] = None
    cPais: Annotated[str, Element] = None
    xPais: Annotated[str, Element] = None
    fone: Annotated[str, Element] = None


class TLocal(ComplexType):
    """Tipo Dados do Local de Retirada ou Entrega // 24/10/08 - tamanho mínimo // v2.0"""
    CNPJ: Annotated[TCnpjOpc, Element] = None
    CPF: Annotated[TCpf, Element] = None
    CNPJ_CPF = Choice("CNPJ", "CPF")
    xNome: Annotated[str, Element] = None
    xLgr: Annotated[str, Element] = None
    nro: Annotated[str, Element] = None
    xCpl: Annotated[str, Element] = None
    xBairro: Annotated[str, Element] = None
    cMun: Annotated[TCodMunIBGE, Element] = None
    xMun: Annotated[str, Element] = None
    UF: Annotated[TUf, Element] = None
    CEP: Annotated[str, Element] = None
    cPais: Annotated[str, Element] = None
    xPais: Annotated[str, Element] = None
    fone: Annotated[str, Element] = None
    email: Annotated[str, Element] = None
    IE: Annotated[TIe, Element] = None


class TInfRespTec(ComplexType):
    """Grupo de informações do responsável técnico pelo sistema de emissão de DF-e"""
    CNPJ: Annotated[TCnpjOpc, Element] = None
    xContato: Annotated[str, Element] = None
    email: Annotated[str, Element] = None
    fone: Annotated[str, Element] = None
    idCSRT: Annotated[str, Element] = None
    hashCSRT: Annotated[base64Binary, Element] = None


class TVeiculo(ComplexType):
    """Tipo Dados do Veículo"""
    placa: Annotated[str, Element] = None
    UF: Annotated[TUf, Element] = None
    RNTC: Annotated[str, Element] = None


class Torig(str):
    """Tipo Origem da mercadoria CST ICMS  origem da mercadoria: 0-Nacional exceto as indicadas nos códigos 3, 4, 5 e 8;
1-Estrangeira - Importação direta; 2-Estrangeira - Adquirida no mercado interno; 3-Nacional, conteudo superior 40% e inferior ou igual a 70%; 4-Nacional, processos produtivos básicos; 5-Nacional, conteudo inferior 40%; 6-Estrangeira - Importação direta, com similar nacional, lista CAMEX; 7-Estrangeira - mercado interno, sem simular,lista CAMEX;8-Nacional, Conteúdo de Importação superior a 70%."""
    pass


class TFinNFe(str):
    """Tipo Finalidade da NF-e (1=Normal; 2=Complementar; 3=Ajuste; 4=Devolução/Retorno)"""
    pass


class TProcEmi(str):
    """Tipo processo de emissão da NF-e"""
    pass


class TCListServ(str):
    """Tipo Código da Lista de Serviços LC 116/2003"""
    pass


class TVerNFe(str):
    """ Tipo Versão da NF-e - 4.00"""
    pass


class TGuid(str):
    """Identificador único (Globally Unique Identifier)"""
    pass


class TIpi(ComplexType):
    """Tipo: Dados do IPI"""
    CNPJProd: Annotated[TCnpj, Element] = None
    cSelo: Annotated[str, Element] = None
    qSelo: Annotated[str, Element] = None
    cEnq: Annotated[str, Element] = None

    class _IPITrib(ComplexType):
        CST: Annotated[str, Element] = None
        vBC: Annotated[TDec_1302, Element] = None
        pIPI: Annotated[TDec_0302a04, Element] = None
        qUnid: Annotated[TDec_1204v, Element] = None
        vUnid: Annotated[TDec_1104, Element] = None
        vIPI: Annotated[TDec_1302, Element] = None

    IPITrib: Annotated[_IPITrib, Element] = None

    class _IPINT(ComplexType):
        CST: Annotated[str, Element] = None

    IPINT: Annotated[_IPINT, Element] = None
    IPITrib_IPINT = Choice("IPITrib", "IPINT")


class TNFe(ComplexType):
    """Tipo Nota Fiscal Eletrônica"""

    class _infNFe(ComplexType):
        """Informações da Nota Fiscal eletrônica"""
        versao: Annotated[TVerNFe, Attribute] = None
        Id: Annotated[str, Attribute(pattern=r'NFe[0-9]{44}')] = None

        class _ide(ComplexType):
            """identificação da NF-e"""
            cUF: Annotated[TCodUfIBGE, Element] = None
            cNF: Annotated[str, Element] = None
            natOp: Annotated[str, Element] = None
            mod: Annotated[TMod, Element] = None
            serie: Annotated[TSerie, Element] = None
            nNF: Annotated[TNF, Element] = None
            dhEmi: Annotated[TDateTimeUTC, Element] = None
            dhSaiEnt: Annotated[TDateTimeUTC, Element] = None
            tpNF: Annotated[str, Element] = None
            idDest: Annotated[str, Element] = None
            cMunFG: Annotated[TCodMunIBGE, Element] = None
            tpImp: Annotated[str, Element] = None
            tpEmis: Annotated[str, Element] = None
            cDV: Annotated[str, Element] = None
            tpAmb: Annotated[TAmb, Element] = None
            finNFe: Annotated[TFinNFe, Element] = None
            indFinal: Annotated[str, Element] = None
            indPres: Annotated[str, Element] = None
            indIntermed: Annotated[str, Element] = None
            procEmi: Annotated[TProcEmi, Element] = None
            verProc: Annotated[str, Element] = None
            dhCont: Annotated[TDateTimeUTC, Element] = None
            xJust: Annotated[str, Element] = None

            class _NFref(ComplexType):
                """Grupo de infromações da NF referenciada"""
                refNFe: Annotated[TChNFe, Element] = None

                class _refNF(ComplexType):
                    """Dados da NF modelo 1/1A referenciada ou NF modelo 2 referenciada"""
                    cUF: Annotated[TCodUfIBGE, Element] = None
                    AAMM: Annotated[str, Element] = None
                    CNPJ: Annotated[TCnpj, Element] = None
                    mod: Annotated[str, Element] = None
                    serie: Annotated[TSerie, Element] = None
                    nNF: Annotated[TNF, Element] = None

                refNF: Annotated[_refNF, Element] = None

                class _refNFP(ComplexType):
                    """Grupo com as informações NF de produtor referenciada"""
                    cUF: Annotated[TCodUfIBGE, Element] = None
                    AAMM: Annotated[str, Element] = None
                    CNPJ: Annotated[TCnpj, Element] = None
                    CPF: Annotated[TCpf, Element] = None
                    CNPJ_CPF = Choice("CNPJ", "CPF")
                    IE: Annotated[TIeDest, Element] = None
                    mod: Annotated[str, Element] = None
                    serie: Annotated[TSerie, Element] = None
                    nNF: Annotated[TNF, Element] = None

                refNFP: Annotated[_refNFP, Element] = None
                refCTe: Annotated[TChNFe, Element] = None

                class _refECF(ComplexType):
                    """Grupo do Cupom Fiscal vinculado à NF-e"""
                    mod: Annotated[str, Element] = None
                    nECF: Annotated[str, Element] = None
                    nCOO: Annotated[str, Element] = None

                refECF: Annotated[_refECF, Element] = None
                refNFe_refNF_refNFP_refCTe_refECF = Choice("refNFe", "refNF", "refNFP", "refCTe", "refECF")

            NFref: Annotated[ElementList[_NFref], Element] = None

        ide: Annotated[_ide, Element] = None

        class _emit(ComplexType):
            """Identificação do emitente"""
            CNPJ: Annotated[TCnpj, Element] = None
            CPF: Annotated[TCpf, Element] = None
            CNPJ_CPF = Choice("CNPJ", "CPF")
            xNome: Annotated[str, Element] = None
            xFant: Annotated[str, Element] = None
            enderEmit: Annotated[TEnderEmi, Element] = None
            IE: Annotated[TIe, Element] = None
            IEST: Annotated[TIeST, Element] = None
            IM: Annotated[str, Element] = None
            CNAE: Annotated[str, Element] = None
            CRT: Annotated[str, Element] = None

        emit: Annotated[_emit, Element] = None

        class _avulsa(ComplexType):
            """Emissão de avulsa, informar os dados do Fisco emitente"""
            CNPJ: Annotated[TCnpj, Element] = None
            xOrgao: Annotated[str, Element] = None
            matr: Annotated[str, Element] = None
            xAgente: Annotated[str, Element] = None
            fone: Annotated[str, Element] = None
            UF: Annotated[TUfEmi, Element] = None
            nDAR: Annotated[str, Element] = None
            dEmi: Annotated[TData, Element] = None
            vDAR: Annotated[TDec_1302, Element] = None
            repEmi: Annotated[str, Element] = None
            dPag: Annotated[TData, Element] = None

        avulsa: Annotated[_avulsa, Element] = None

        class _dest(ComplexType):
            """Identificação do Destinatário"""
            CNPJ: Annotated[TCnpj, Element] = None
            CPF: Annotated[TCpf, Element] = None
            idEstrangeiro: Annotated[str, Element] = None
            CNPJ_CPF_idEstrangeiro = Choice("CNPJ", "CPF", "idEstrangeiro")
            xNome: Annotated[str, Element] = None
            enderDest: Annotated[TEndereco, Element] = None
            indIEDest: Annotated[str, Element] = None
            IE: Annotated[TIeDestNaoIsento, Element] = None
            ISUF: Annotated[str, Element] = None
            IM: Annotated[str, Element] = None
            email: Annotated[str, Element] = None

        dest: Annotated[_dest, Element] = None
        retirada: Annotated[TLocal, Element] = None
        entrega: Annotated[TLocal, Element] = None

        class _autXML(ComplexType):
            """Pessoas autorizadas para o download do XML da NF-e"""
            CNPJ: Annotated[TCnpj, Element] = None
            CPF: Annotated[TCpf, Element] = None
            CNPJ_CPF = Choice("CNPJ", "CPF")

        autXML: Annotated[ElementList[_autXML], Element] = None

        class _det(ComplexType):
            """Dados dos detalhes da NF-e"""
            nItem: Annotated[str, Attribute(pattern=r'[1-9]{1}[0-9]{0,1}|[1-8]{1}[0-9]{2}|[9]{1}[0-8]{1}[0-9]{1}|[9]{1}[9]{1}[0]{1}')] = None

            class _prod(ComplexType):
                """Dados dos produtos e serviços da NF-e"""
                cProd: Annotated[str, Element] = None
                cEAN: Annotated[str, Element] = None
                cBarra: Annotated[str, Element] = None
                xProd: Annotated[str, Element] = None
                NCM: Annotated[str, Element] = None
                NVE: Annotated[ElementList[str], Element] = None
                CEST: Annotated[str, Element] = None
                indEscala: Annotated[str, Element] = None
                CNPJFab: Annotated[TCnpj, Element] = None
                cBenef: Annotated[str, Element] = None
                EXTIPI: Annotated[str, Element] = None
                CFOP: Annotated[str, Element] = None
                uCom: Annotated[str, Element] = None
                qCom: Annotated[TDec_1104v, Element] = None
                vUnCom: Annotated[TDec_1110v, Element] = None
                vProd: Annotated[TDec_1302, Element] = None
                cEANTrib: Annotated[str, Element] = None
                cBarraTrib: Annotated[str, Element] = None
                uTrib: Annotated[str, Element] = None
                qTrib: Annotated[TDec_1104v, Element] = None
                vUnTrib: Annotated[TDec_1110v, Element] = None
                vFrete: Annotated[TDec_1302Opc, Element] = None
                vSeg: Annotated[TDec_1302Opc, Element] = None
                vDesc: Annotated[TDec_1302Opc, Element] = None
                vOutro: Annotated[TDec_1302Opc, Element] = None
                indTot: Annotated[str, Element] = None

                class _DI(ComplexType):
                    """Delcaração de Importação
(NT 2011/004)"""
                    nDI: Annotated[str, Element] = None
                    dDI: Annotated[TData, Element] = None
                    xLocDesemb: Annotated[str, Element] = None
                    UFDesemb: Annotated[TUfEmi, Element] = None
                    dDesemb: Annotated[TData, Element] = None
                    tpViaTransp: Annotated[str, Element] = None
                    vAFRMM: Annotated[TDec_1302, Element] = None
                    tpIntermedio: Annotated[str, Element] = None
                    CNPJ: Annotated[TCnpj, Element] = None
                    UFTerceiro: Annotated[TUfEmi, Element] = None
                    cExportador: Annotated[str, Element] = None

                    class _adi(ComplexType):
                        """Adições (NT 2011/004)"""
                        nAdicao: Annotated[str, Element] = None
                        nSeqAdic: Annotated[str, Element] = None
                        cFabricante: Annotated[str, Element] = None
                        vDescDI: Annotated[TDec_1302Opc, Element] = None
                        nDraw: Annotated[str, Element] = None

                    adi: Annotated[ElementList[_adi], Element] = None

                DI: Annotated[ElementList[_DI], Element] = None

                class _detExport(ComplexType):
                    """Detalhe da exportação"""
                    nDraw: Annotated[str, Element] = None

                    class _exportInd(ComplexType):
                        """Exportação indireta"""
                        nRE: Annotated[str, Element] = None
                        chNFe: Annotated[TChNFe, Element] = None
                        qExport: Annotated[TDec_1104v, Element] = None

                    exportInd: Annotated[_exportInd, Element] = None

                detExport: Annotated[ElementList[_detExport], Element] = None
                xPed: Annotated[str, Element] = None
                nItemPed: Annotated[str, Element] = None
                nFCI: Annotated[TGuid, Element] = None

                class _rastro(ComplexType):
                    nLote: Annotated[str, Element] = None
                    qLote: Annotated[TDec_0803v, Element] = None
                    dFab: Annotated[TData, Element] = None
                    dVal: Annotated[TData, Element] = None
                    cAgreg: Annotated[str, Element] = None

                rastro: Annotated[ElementList[_rastro], Element] = None

                class _veicProd(ComplexType):
                    """Veículos novos"""
                    tpOp: Annotated[str, Element] = None
                    chassi: Annotated[str, Element] = None
                    cCor: Annotated[str, Element] = None
                    xCor: Annotated[str, Element] = None
                    pot: Annotated[str, Element] = None
                    cilin: Annotated[str, Element] = None
                    pesoL: Annotated[str, Element] = None
                    pesoB: Annotated[str, Element] = None
                    nSerie: Annotated[str, Element] = None
                    tpComb: Annotated[str, Element] = None
                    nMotor: Annotated[str, Element] = None
                    CMT: Annotated[str, Element] = None
                    dist: Annotated[str, Element] = None
                    anoMod: Annotated[str, Element] = None
                    anoFab: Annotated[str, Element] = None
                    tpPint: Annotated[str, Element] = None
                    tpVeic: Annotated[str, Element] = None
                    espVeic: Annotated[str, Element] = None
                    VIN: Annotated[str, Element] = None
                    condVeic: Annotated[str, Element] = None
                    cMod: Annotated[str, Element] = None
                    cCorDENATRAN: Annotated[str, Element] = None
                    lota: Annotated[str, Element] = None
                    tpRest: Annotated[str, Element] = None

                veicProd: Annotated[_veicProd, Element] = None

                class _med(ComplexType):
                    """grupo do detalhamento de Medicamentos e de matérias-primas farmacêuticas"""
                    cProdANVISA: Annotated[str, Element] = None
                    xMotivoIsencao: Annotated[str, Element] = None
                    vPMC: Annotated[TDec_1302, Element] = None

                med: Annotated[_med, Element] = None

                class _arma(ComplexType):
                    """Armamentos"""
                    tpArma: Annotated[str, Element] = None
                    nSerie: Annotated[str, Element] = None
                    nCano: Annotated[str, Element] = None
                    descr: Annotated[str, Element] = None

                arma: Annotated[ElementList[_arma], Element] = None

                class _comb(ComplexType):
                    """Informar apenas para operações com combustíveis líquidos"""
                    cProdANP: Annotated[str, Element] = None
                    descANP: Annotated[str, Element] = None
                    pGLP: Annotated[TDec_0302a04Max100, Element] = None
                    pGNn: Annotated[TDec_0302a04Max100, Element] = None
                    pGNi: Annotated[TDec_0302a04Max100, Element] = None
                    vPart: Annotated[TDec_1302, Element] = None
                    CODIF: Annotated[str, Element] = None
                    qTemp: Annotated[TDec_1204temperatura, Element] = None
                    UFCons: Annotated[TUf, Element] = None

                    class _CIDE(ComplexType):
                        """CIDE Combustíveis"""
                        qBCProd: Annotated[TDec_1204v, Element] = None
                        vAliqProd: Annotated[TDec_1104, Element] = None
                        vCIDE: Annotated[TDec_1302, Element] = None

                    CIDE: Annotated[_CIDE, Element] = None

                    class _encerrante(ComplexType):
                        """Informações do grupo de \"encerrante\""""
                        nBico: Annotated[str, Element] = None
                        nBomba: Annotated[str, Element] = None
                        nTanque: Annotated[str, Element] = None
                        vEncIni: Annotated[TDec_1203, Element] = None
                        vEncFin: Annotated[TDec_1203, Element] = None

                    encerrante: Annotated[_encerrante, Element] = None

                comb: Annotated[_comb, Element] = None
                nRECOPI: Annotated[str, Element] = None
                veicProd_med_arma_comb_nRECOPI = Choice("veicProd", "med", "arma", "comb", "nRECOPI")

            prod: Annotated[_prod, Element] = None

            class _imposto(ComplexType):
                """Tributos incidentes nos produtos ou serviços da NF-e"""
                vTotTrib: Annotated[TDec_1302, Element] = None

                class _ICMS(ComplexType):
                    """Dados do ICMS Normal e ST"""

                    class _ICMS00(ComplexType):
                        """Tributação pelo ICMS
00 - Tributada integralmente"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        pFCP: Annotated[TDec_0302a04Opc, Element] = None
                        vFCP: Annotated[TDec_1302, Element] = None

                    ICMS00: Annotated[_ICMS00, Element] = None

                    class _ICMS10(ComplexType):
                        """Tributação pelo ICMS
10 - Tributada e com cobrança do ICMS por substituição tributária"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        vBCFCP: Annotated[TDec_1302, Element] = None
                        pFCP: Annotated[TDec_0302a04Opc, Element] = None
                        vFCP: Annotated[TDec_1302, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None
                        vICMSSTDeson: Annotated[TDec_1302, Element] = None
                        motDesICMSST: Annotated[str, Element] = None

                    ICMS10: Annotated[_ICMS10, Element] = None

                    class _ICMS20(ComplexType):
                        """Tributção pelo ICMS
20 - Com redução de base de cálculo"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        pRedBC: Annotated[TDec_0302a04, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        vBCFCP: Annotated[TDec_1302, Element] = None
                        pFCP: Annotated[TDec_0302a04Opc, Element] = None
                        vFCP: Annotated[TDec_1302, Element] = None
                        vICMSDeson: Annotated[TDec_1302, Element] = None
                        motDesICMS: Annotated[str, Element] = None
                        indDeduzDeson: Annotated[str, Element] = None

                    ICMS20: Annotated[_ICMS20, Element] = None

                    class _ICMS30(ComplexType):
                        """Tributação pelo ICMS
30 - Isenta ou não tributada e com cobrança do ICMS por substituição tributária"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None
                        vICMSDeson: Annotated[TDec_1302, Element] = None
                        motDesICMS: Annotated[str, Element] = None
                        indDeduzDeson: Annotated[str, Element] = None

                    ICMS30: Annotated[_ICMS30, Element] = None

                    class _ICMS40(ComplexType):
                        """Tributação pelo ICMS
40 - Isenta 
41 - Não tributada 
50 - Suspensão"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        vICMSDeson: Annotated[TDec_1302, Element] = None
                        motDesICMS: Annotated[str, Element] = None
                        indDeduzDeson: Annotated[str, Element] = None

                    ICMS40: Annotated[_ICMS40, Element] = None

                    class _ICMS51(ComplexType):
                        """Tributção pelo ICMS
51 - Diferimento
A exigência do preenchimento das informações do ICMS diferido fica à critério de cada UF."""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        pRedBC: Annotated[TDec_0302a04, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMSOp: Annotated[TDec_1302, Element] = None
                        pDif: Annotated[TDec_0302a04Max100, Element] = None
                        vICMSDif: Annotated[TDec_1302, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        vBCFCP: Annotated[TDec_1302, Element] = None
                        pFCP: Annotated[TDec_0302a04Opc, Element] = None
                        vFCP: Annotated[TDec_1302, Element] = None
                        pFCPDif: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPDif: Annotated[TDec_1302, Element] = None
                        vFCPEfet: Annotated[TDec_1302, Element] = None

                    ICMS51: Annotated[_ICMS51, Element] = None

                    class _ICMS60(ComplexType):
                        """Tributação pelo ICMS
60 - ICMS cobrado anteriormente por substituição tributária"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        vBCSTRet: Annotated[TDec_1302, Element] = None
                        pST: Annotated[TDec_0302a04Opc, Element] = None
                        vICMSSubstituto: Annotated[TDec_1302, Element] = None
                        vICMSSTRet: Annotated[TDec_1302, Element] = None
                        vBCFCPSTRet: Annotated[TDec_1302, Element] = None
                        pFCPSTRet: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPSTRet: Annotated[TDec_1302, Element] = None
                        pRedBCEfet: Annotated[TDec_0302a04Opc, Element] = None
                        vBCEfet: Annotated[TDec_1302, Element] = None
                        pICMSEfet: Annotated[TDec_0302a04Opc, Element] = None
                        vICMSEfet: Annotated[TDec_1302, Element] = None

                    ICMS60: Annotated[_ICMS60, Element] = None

                    class _ICMS70(ComplexType):
                        """Tributação pelo ICMS 
70 - Com redução de base de cálculo e cobrança do ICMS por substituição tributária"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        pRedBC: Annotated[TDec_0302a04, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        vBCFCP: Annotated[TDec_1302, Element] = None
                        pFCP: Annotated[TDec_0302a04Opc, Element] = None
                        vFCP: Annotated[TDec_1302, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None
                        vICMSDeson: Annotated[TDec_1302, Element] = None
                        motDesICMS: Annotated[str, Element] = None
                        indDeduzDeson: Annotated[str, Element] = None
                        vICMSSTDeson: Annotated[TDec_1302, Element] = None
                        motDesICMSST: Annotated[str, Element] = None

                    ICMS70: Annotated[_ICMS70, Element] = None

                    class _ICMS90(ComplexType):
                        """Tributação pelo ICMS
90 - Outras"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pRedBC: Annotated[TDec_0302a04Opc, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        vBCFCP: Annotated[TDec_1302, Element] = None
                        pFCP: Annotated[TDec_0302a04Opc, Element] = None
                        vFCP: Annotated[TDec_1302, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None
                        vICMSDeson: Annotated[TDec_1302, Element] = None
                        motDesICMS: Annotated[str, Element] = None
                        indDeduzDeson: Annotated[str, Element] = None
                        vICMSSTDeson: Annotated[TDec_1302, Element] = None
                        motDesICMSST: Annotated[str, Element] = None

                    ICMS90: Annotated[_ICMS90, Element] = None

                    class _ICMSPart(ComplexType):
                        """Partilha do ICMS entre a UF de origem e UF de destino ou a UF definida na legislação
Operação interestadual para consumidor final com partilha do ICMS  devido na operação entre a UF de origem e a UF do destinatário ou ou a UF definida na legislação. (Ex. UF da concessionária de entrega do  veículos)"""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pRedBC: Annotated[TDec_0302a04Opc, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        pBCOp: Annotated[TDec_0302a04Opc, Element] = None
                        UFST: Annotated[TUf, Element] = None

                    ICMSPart: Annotated[_ICMSPart, Element] = None

                    class _ICMSST(ComplexType):
                        """Grupo de informação do ICMSST devido para a UF de destino, nas operações interestaduais de produtos que tiveram retenção antecipada de ICMS por ST na UF do remetente. Repasse via Substituto Tributário."""
                        orig: Annotated[Torig, Element] = None
                        CST: Annotated[str, Element] = None
                        vBCSTRet: Annotated[TDec_1302, Element] = None
                        pST: Annotated[TDec_0302a04Opc, Element] = None
                        vICMSSubstituto: Annotated[TDec_1302, Element] = None
                        vICMSSTRet: Annotated[TDec_1302, Element] = None
                        vBCFCPSTRet: Annotated[TDec_1302, Element] = None
                        pFCPSTRet: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPSTRet: Annotated[TDec_1302, Element] = None
                        vBCSTDest: Annotated[TDec_1302, Element] = None
                        vICMSSTDest: Annotated[TDec_1302, Element] = None
                        pRedBCEfet: Annotated[TDec_0302a04Opc, Element] = None
                        vBCEfet: Annotated[TDec_1302, Element] = None
                        pICMSEfet: Annotated[TDec_0302a04Opc, Element] = None
                        vICMSEfet: Annotated[TDec_1302, Element] = None

                    ICMSST: Annotated[_ICMSST, Element] = None

                    class _ICMSSN101(ComplexType):
                        """Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=101 (v.2.0)"""
                        orig: Annotated[Torig, Element] = None
                        CSOSN: Annotated[str, Element] = None
                        pCredSN: Annotated[TDec_0302a04, Element] = None
                        vCredICMSSN: Annotated[TDec_1302, Element] = None

                    ICMSSN101: Annotated[_ICMSSN101, Element] = None

                    class _ICMSSN102(ComplexType):
                        """Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=102, 103, 300 ou 400 (v.2.0))"""
                        orig: Annotated[Torig, Element] = None
                        CSOSN: Annotated[str, Element] = None

                    ICMSSN102: Annotated[_ICMSSN102, Element] = None

                    class _ICMSSN201(ComplexType):
                        """Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=201 (v.2.0)"""
                        orig: Annotated[Torig, Element] = None
                        CSOSN: Annotated[str, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None
                        pCredSN: Annotated[TDec_0302a04, Element] = None
                        vCredICMSSN: Annotated[TDec_1302, Element] = None

                    ICMSSN201: Annotated[_ICMSSN201, Element] = None

                    class _ICMSSN202(ComplexType):
                        """Tributação do ICMS pelo SIMPLES NACIONAL e CSOSN=202 ou 203 (v.2.0)"""
                        orig: Annotated[Torig, Element] = None
                        CSOSN: Annotated[str, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None

                    ICMSSN202: Annotated[_ICMSSN202, Element] = None

                    class _ICMSSN500(ComplexType):
                        """Tributação do ICMS pelo SIMPLES NACIONAL,CRT=1 – Simples Nacional e CSOSN=500 (v.2.0)"""
                        orig: Annotated[Torig, Element] = None
                        CSOSN: Annotated[str, Element] = None
                        vBCSTRet: Annotated[TDec_1302, Element] = None
                        pST: Annotated[TDec_0302a04Opc, Element] = None
                        vICMSSubstituto: Annotated[TDec_1302, Element] = None
                        vICMSSTRet: Annotated[TDec_1302, Element] = None
                        vBCFCPSTRet: Annotated[TDec_1302, Element] = None
                        pFCPSTRet: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPSTRet: Annotated[TDec_1302, Element] = None
                        pRedBCEfet: Annotated[TDec_0302a04Opc, Element] = None
                        vBCEfet: Annotated[TDec_1302, Element] = None
                        pICMSEfet: Annotated[TDec_0302a04Opc, Element] = None
                        vICMSEfet: Annotated[TDec_1302, Element] = None

                    ICMSSN500: Annotated[_ICMSSN500, Element] = None

                    class _ICMSSN900(ComplexType):
                        """Tributação do ICMS pelo SIMPLES NACIONAL, CRT=1 – Simples Nacional e CSOSN=900 (v2.0)"""
                        orig: Annotated[Torig, Element] = None
                        CSOSN: Annotated[str, Element] = None
                        modBC: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pRedBC: Annotated[TDec_0302a04Opc, Element] = None
                        pICMS: Annotated[TDec_0302a04, Element] = None
                        vICMS: Annotated[TDec_1302, Element] = None
                        modBCST: Annotated[str, Element] = None
                        pMVAST: Annotated[TDec_0302a04Opc, Element] = None
                        pRedBCST: Annotated[TDec_0302a04Opc, Element] = None
                        vBCST: Annotated[TDec_1302, Element] = None
                        pICMSST: Annotated[TDec_0302a04, Element] = None
                        vICMSST: Annotated[TDec_1302, Element] = None
                        vBCFCPST: Annotated[TDec_1302, Element] = None
                        pFCPST: Annotated[TDec_0302a04Opc, Element] = None
                        vFCPST: Annotated[TDec_1302, Element] = None
                        pCredSN: Annotated[TDec_0302a04, Element] = None
                        vCredICMSSN: Annotated[TDec_1302, Element] = None

                    ICMSSN900: Annotated[_ICMSSN900, Element] = None
                    ICMS00_ICMS10_ICMS20_ICMS30_ICMS40_ICMS51_ICMS60_ICMS70_ICMS90_ICMSPart_ICMSST_ICMSSN101_ICMSSN102_ICMSSN201_ICMSSN202_ICMSSN500_ICMSSN900 = Choice("ICMS00", "ICMS10", "ICMS20", "ICMS30", "ICMS40", "ICMS51", "ICMS60", "ICMS70", "ICMS90", "ICMSPart", "ICMSST", "ICMSSN101", "ICMSSN102", "ICMSSN201", "ICMSSN202", "ICMSSN500", "ICMSSN900")

                ICMS: Annotated[_ICMS, Element] = None
                IPI: Annotated[TIpi, Element] = None

                class _II(ComplexType):
                    """Dados do Imposto de Importação"""
                    vBC: Annotated[TDec_1302, Element] = None
                    vDespAdu: Annotated[TDec_1302, Element] = None
                    vII: Annotated[TDec_1302, Element] = None
                    vIOF: Annotated[TDec_1302, Element] = None

                II: Annotated[_II, Element] = None
                IPI: Annotated[TIpi, Element] = None

                class _ISSQN(ComplexType):
                    """ISSQN"""
                    vBC: Annotated[TDec_1302, Element] = None
                    vAliq: Annotated[TDec_0302a04, Element] = None
                    vISSQN: Annotated[TDec_1302, Element] = None
                    cMunFG: Annotated[TCodMunIBGE, Element] = None
                    cListServ: Annotated[TCListServ, Element] = None
                    vDeducao: Annotated[TDec_1302Opc, Element] = None
                    vOutro: Annotated[TDec_1302Opc, Element] = None
                    vDescIncond: Annotated[TDec_1302Opc, Element] = None
                    vDescCond: Annotated[TDec_1302Opc, Element] = None
                    vISSRet: Annotated[TDec_1302Opc, Element] = None
                    indISS: Annotated[str, Element] = None
                    cServico: Annotated[str, Element] = None
                    cMun: Annotated[TCodMunIBGE, Element] = None
                    cPais: Annotated[str, Element] = None
                    nProcesso: Annotated[str, Element] = None
                    indIncentivo: Annotated[str, Element] = None

                ISSQN: Annotated[_ISSQN, Element] = None

                class _PIS(ComplexType):
                    """Dados do PIS"""

                    class _PISAliq(ComplexType):
                        """Código de Situação Tributária do PIS.
 01 – Operação Tributável - Base de Cálculo = Valor da Operação Alíquota Normal (Cumulativo/Não Cumulativo);
02 - Operação Tributável - Base de Calculo = Valor da Operação (Alíquota Diferenciada);"""
                        CST: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pPIS: Annotated[TDec_0302a04, Element] = None
                        vPIS: Annotated[TDec_1302, Element] = None

                    PISAliq: Annotated[_PISAliq, Element] = None

                    class _PISQtde(ComplexType):
                        """Código de Situação Tributária do PIS.
03 - Operação Tributável - Base de Calculo = Quantidade Vendida x Alíquota por Unidade de Produto;"""
                        CST: Annotated[str, Element] = None
                        qBCProd: Annotated[TDec_1204v, Element] = None
                        vAliqProd: Annotated[TDec_1104v, Element] = None
                        vPIS: Annotated[TDec_1302, Element] = None

                    PISQtde: Annotated[_PISQtde, Element] = None

                    class _PISNT(ComplexType):
                        """Código de Situação Tributária do PIS.
04 - Operação Tributável - Tributação Monofásica - (Alíquota Zero);
06 - Operação Tributável - Alíquota Zero;
07 - Operação Isenta da contribuição;
08 - Operação Sem Incidência da contribuição;
09 - Operação com suspensão da contribuição;"""
                        CST: Annotated[str, Element] = None

                    PISNT: Annotated[_PISNT, Element] = None

                    class _PISOutr(ComplexType):
                        """Código de Situação Tributária do PIS.
99 - Outras Operações."""
                        CST: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pPIS: Annotated[TDec_0302a04, Element] = None
                        qBCProd: Annotated[TDec_1204v, Element] = None
                        vAliqProd: Annotated[TDec_1104v, Element] = None
                        vPIS: Annotated[TDec_1302, Element] = None

                    PISOutr: Annotated[_PISOutr, Element] = None
                    PISAliq_PISQtde_PISNT_PISOutr = Choice("PISAliq", "PISQtde", "PISNT", "PISOutr")

                PIS: Annotated[_PIS, Element] = None

                class _PISST(ComplexType):
                    """Dados do PIS Substituição Tributária"""
                    vBC: Annotated[TDec_1302Opc, Element] = None
                    pPIS: Annotated[TDec_0302a04, Element] = None
                    qBCProd: Annotated[TDec_1204, Element] = None
                    vAliqProd: Annotated[TDec_1104, Element] = None
                    vPIS: Annotated[TDec_1302, Element] = None
                    indSomaPISST: Annotated[str, Element] = None

                PISST: Annotated[_PISST, Element] = None

                class _COFINS(ComplexType):
                    """Dados do COFINS"""

                    class _COFINSAliq(ComplexType):
                        """Código de Situação Tributária do COFINS.
 01 – Operação Tributável - Base de Cálculo = Valor da Operação Alíquota Normal (Cumulativo/Não Cumulativo);
02 - Operação Tributável - Base de Calculo = Valor da Operação (Alíquota Diferenciada);"""
                        CST: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pCOFINS: Annotated[TDec_0302a04, Element] = None
                        vCOFINS: Annotated[TDec_1302, Element] = None

                    COFINSAliq: Annotated[_COFINSAliq, Element] = None

                    class _COFINSQtde(ComplexType):
                        """Código de Situação Tributária do COFINS.
03 - Operação Tributável - Base de Calculo = Quantidade Vendida x Alíquota por Unidade de Produto;"""
                        CST: Annotated[str, Element] = None
                        qBCProd: Annotated[TDec_1204v, Element] = None
                        vAliqProd: Annotated[TDec_1104v, Element] = None
                        vCOFINS: Annotated[TDec_1302, Element] = None

                    COFINSQtde: Annotated[_COFINSQtde, Element] = None

                    class _COFINSNT(ComplexType):
                        """Código de Situação Tributária do COFINS:
04 - Operação Tributável - Tributação Monofásica - (Alíquota Zero);
06 - Operação Tributável - Alíquota Zero;
07 - Operação Isenta da contribuição;
08 - Operação Sem Incidência da contribuição;
09 - Operação com suspensão da contribuição;"""
                        CST: Annotated[str, Element] = None

                    COFINSNT: Annotated[_COFINSNT, Element] = None

                    class _COFINSOutr(ComplexType):
                        """Código de Situação Tributária do COFINS:
49 - Outras Operações de Saída
50 - Operação com Direito a Crédito - Vinculada Exclusivamente a Receita Tributada no Mercado Interno
51 - Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno
52 - Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação
53 - Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno
54 - Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação
55 - Operação com Direito a Crédito - Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação
56 - Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação
60 - Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno
61 - Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita Não-Tributada no Mercado Interno
62 - Crédito Presumido - Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação
63 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno
64 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação
65 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação
66 - Crédito Presumido - Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação
67 - Crédito Presumido - Outras Operações
70 - Operação de Aquisição sem Direito a Crédito
71 - Operação de Aquisição com Isenção
72 - Operação de Aquisição com Suspensão
73 - Operação de Aquisição a Alíquota Zero
74 - Operação de Aquisição sem Incidência da Contribuição
75 - Operação de Aquisição por Substituição Tributária
98 - Outras Operações de Entrada
99 - Outras Operações."""
                        CST: Annotated[str, Element] = None
                        vBC: Annotated[TDec_1302, Element] = None
                        pCOFINS: Annotated[TDec_0302a04, Element] = None
                        qBCProd: Annotated[TDec_1204v, Element] = None
                        vAliqProd: Annotated[TDec_1104v, Element] = None
                        vCOFINS: Annotated[TDec_1302, Element] = None

                    COFINSOutr: Annotated[_COFINSOutr, Element] = None
                    COFINSAliq_COFINSQtde_COFINSNT_COFINSOutr = Choice("COFINSAliq", "COFINSQtde", "COFINSNT", "COFINSOutr")

                COFINS: Annotated[_COFINS, Element] = None

                class _COFINSST(ComplexType):
                    """Dados do COFINS da
Substituição Tributaria;"""
                    vBC: Annotated[TDec_1302, Element] = None
                    pCOFINS: Annotated[TDec_0302a04, Element] = None
                    qBCProd: Annotated[TDec_1204, Element] = None
                    vAliqProd: Annotated[TDec_1104, Element] = None
                    vCOFINS: Annotated[TDec_1302, Element] = None
                    indSomaCOFINSST: Annotated[str, Element] = None

                COFINSST: Annotated[_COFINSST, Element] = None

                class _ICMSUFDest(ComplexType):
                    """Grupo a ser informado nas vendas interestarduais para consumidor final, não contribuinte de ICMS"""
                    vBCUFDest: Annotated[TDec_1302, Element] = None
                    vBCFCPUFDest: Annotated[TDec_1302, Element] = None
                    pFCPUFDest: Annotated[TDec_0302a04, Element] = None
                    pICMSUFDest: Annotated[TDec_0302a04, Element] = None
                    pICMSInter: Annotated[str, Element] = None
                    pICMSInterPart: Annotated[TDec_0302a04, Element] = None
                    vFCPUFDest: Annotated[TDec_1302, Element] = None
                    vICMSUFDest: Annotated[TDec_1302, Element] = None
                    vICMSUFRemet: Annotated[TDec_1302, Element] = None

                ICMSUFDest: Annotated[_ICMSUFDest, Element] = None

            imposto: Annotated[_imposto, Element] = None

            class _impostoDevol(ComplexType):
                pDevol: Annotated[TDec_0302Max100, Element] = None

                class _IPI(ComplexType):
                    """Informação de IPI devolvido"""
                    vIPIDevol: Annotated[TDec_1302, Element] = None

                IPI: Annotated[_IPI, Element] = None

            impostoDevol: Annotated[_impostoDevol, Element] = None
            infAdProd: Annotated[str, Element] = None

        det: Annotated[ElementList[_det], Element] = None

        class _total(ComplexType):
            """Dados dos totais da NF-e"""

            class _ICMSTot(ComplexType):
                """Totais referentes ao ICMS"""
                vBC: Annotated[TDec_1302, Element] = None
                vICMS: Annotated[TDec_1302, Element] = None
                vICMSDeson: Annotated[TDec_1302, Element] = None
                vFCPUFDest: Annotated[TDec_1302, Element] = None
                vICMSUFDest: Annotated[TDec_1302, Element] = None
                vICMSUFRemet: Annotated[TDec_1302, Element] = None
                vFCP: Annotated[TDec_1302, Element] = None
                vBCST: Annotated[TDec_1302, Element] = None
                vST: Annotated[TDec_1302, Element] = None
                vFCPST: Annotated[TDec_1302, Element] = None
                vFCPSTRet: Annotated[TDec_1302, Element] = None
                vProd: Annotated[TDec_1302, Element] = None
                vFrete: Annotated[TDec_1302, Element] = None
                vSeg: Annotated[TDec_1302, Element] = None
                vDesc: Annotated[TDec_1302, Element] = None
                vII: Annotated[TDec_1302, Element] = None
                vIPI: Annotated[TDec_1302, Element] = None
                vIPIDevol: Annotated[TDec_1302, Element] = None
                vPIS: Annotated[TDec_1302, Element] = None
                vCOFINS: Annotated[TDec_1302, Element] = None
                vOutro: Annotated[TDec_1302, Element] = None
                vNF: Annotated[TDec_1302, Element] = None
                vTotTrib: Annotated[TDec_1302, Element] = None

            ICMSTot: Annotated[_ICMSTot, Element] = None

            class _ISSQNtot(ComplexType):
                """Totais referentes ao ISSQN"""
                vServ: Annotated[TDec_1302Opc, Element] = None
                vBC: Annotated[TDec_1302Opc, Element] = None
                vISS: Annotated[TDec_1302Opc, Element] = None
                vPIS: Annotated[TDec_1302Opc, Element] = None
                vCOFINS: Annotated[TDec_1302Opc, Element] = None
                dCompet: Annotated[TData, Element] = None
                vDeducao: Annotated[TDec_1302Opc, Element] = None
                vOutro: Annotated[TDec_1302Opc, Element] = None
                vDescIncond: Annotated[TDec_1302Opc, Element] = None
                vDescCond: Annotated[TDec_1302Opc, Element] = None
                vISSRet: Annotated[TDec_1302Opc, Element] = None
                cRegTrib: Annotated[str, Element] = None

            ISSQNtot: Annotated[_ISSQNtot, Element] = None

            class _retTrib(ComplexType):
                """Retenção de Tributos Federais"""
                vRetPIS: Annotated[TDec_1302Opc, Element] = None
                vRetCOFINS: Annotated[TDec_1302Opc, Element] = None
                vRetCSLL: Annotated[TDec_1302Opc, Element] = None
                vBCIRRF: Annotated[TDec_1302Opc, Element] = None
                vIRRF: Annotated[TDec_1302Opc, Element] = None
                vBCRetPrev: Annotated[TDec_1302Opc, Element] = None
                vRetPrev: Annotated[TDec_1302Opc, Element] = None

            retTrib: Annotated[_retTrib, Element] = None

        total: Annotated[_total, Element] = None

        class _transp(ComplexType):
            """Dados dos transportes da NF-e"""
            modFrete: Annotated[str, Element] = None

            class _transporta(ComplexType):
                """Dados do transportador"""
                CNPJ: Annotated[TCnpj, Element] = None
                CPF: Annotated[TCpf, Element] = None
                CNPJ_CPF = Choice("CNPJ", "CPF")
                xNome: Annotated[str, Element] = None
                IE: Annotated[TIeDest, Element] = None
                xEnder: Annotated[str, Element] = None
                xMun: Annotated[str, Element] = None
                UF: Annotated[TUf, Element] = None

            transporta: Annotated[_transporta, Element] = None

            class _retTransp(ComplexType):
                """Dados da retenção  ICMS do Transporte"""
                vServ: Annotated[TDec_1302, Element] = None
                vBCRet: Annotated[TDec_1302, Element] = None
                pICMSRet: Annotated[TDec_0302a04, Element] = None
                vICMSRet: Annotated[TDec_1302, Element] = None
                CFOP: Annotated[str, Element] = None
                cMunFG: Annotated[TCodMunIBGE, Element] = None

            retTransp: Annotated[_retTransp, Element] = None
            veicTransp: Annotated[TVeiculo, Element] = None
            reboque: Annotated[ElementList[TVeiculo], Element] = None
            vagao: Annotated[str, Element] = None
            balsa: Annotated[str, Element] = None
            vagao_balsa = Choice("vagao", "balsa")

            class _vol(ComplexType):
                """Dados dos volumes"""
                qVol: Annotated[str, Element] = None
                esp: Annotated[str, Element] = None
                marca: Annotated[str, Element] = None
                nVol: Annotated[str, Element] = None
                pesoL: Annotated[TDec_1203, Element] = None
                pesoB: Annotated[TDec_1203, Element] = None

                class _lacres(ComplexType):
                    nLacre: Annotated[str, Element] = None

                lacres: Annotated[ElementList[_lacres], Element] = None

            vol: Annotated[ElementList[_vol], Element] = None

        transp: Annotated[_transp, Element] = None

        class _cobr(ComplexType):
            """Dados da cobrança da NF-e"""

            class _fat(ComplexType):
                """Dados da fatura"""
                nFat: Annotated[str, Element] = None
                vOrig: Annotated[TDec_1302, Element] = None
                vDesc: Annotated[TDec_1302, Element] = None
                vLiq: Annotated[TDec_1302, Element] = None

            fat: Annotated[_fat, Element] = None

            class _dup(ComplexType):
                """Dados das duplicatas NT 2011/004"""
                nDup: Annotated[str, Element] = None
                dVenc: Annotated[TData, Element] = None
                vDup: Annotated[TDec_1302Opc, Element] = None

            dup: Annotated[ElementList[_dup], Element] = None

        cobr: Annotated[_cobr, Element] = None

        class _pag(ComplexType):
            """Dados de Pagamento. Obrigatório apenas para (NFC-e) NT 2012/004"""

            class _detPag(ComplexType):
                """Grupo de detalhamento da forma de pagamento."""
                indPag: Annotated[str, Element] = None
                tPag: Annotated[str, Element] = None
                xPag: Annotated[str, Element] = None
                vPag: Annotated[TDec_1302, Element] = None

                class _card(ComplexType):
                    """Grupo de Cartões"""
                    tpIntegra: Annotated[str, Element] = None
                    CNPJ: Annotated[TCnpj, Element] = None
                    tBand: Annotated[str, Element] = None
                    cAut: Annotated[str, Element] = None

                card: Annotated[_card, Element] = None

            detPag: Annotated[ElementList[_detPag], Element] = None
            vTroco: Annotated[TDec_1302, Element] = None

        pag: Annotated[_pag, Element] = None

        class _infIntermed(ComplexType):
            """Grupo de Informações do Intermediador da Transação"""
            CNPJ: Annotated[TCnpj, Element] = None
            idCadIntTran: Annotated[str, Element] = None

        infIntermed: Annotated[_infIntermed, Element] = None

        class _infAdic(ComplexType):
            """Informações adicionais da NF-e"""
            infAdFisco: Annotated[str, Element] = None
            infCpl: Annotated[str, Element] = None

            class _obsCont(ComplexType):
                """Campo de uso livre do contribuinte
informar o nome do campo no atributo xCampo
e o conteúdo do campo no xTexto"""
                xCampo: Annotated[str, Attribute(min_length=1, max_length=20)] = None
                xTexto: Annotated[str, Element] = None

            obsCont: Annotated[ElementList[_obsCont], Element] = None

            class _obsFisco(ComplexType):
                """Campo de uso exclusivo do Fisco
informar o nome do campo no atributo xCampo
e o conteúdo do campo no xTexto"""
                xCampo: Annotated[str, Attribute(min_length=1, max_length=20)] = None
                xTexto: Annotated[str, Element] = None

            obsFisco: Annotated[ElementList[_obsFisco], Element] = None

            class _procRef(ComplexType):
                """Grupo de informações do  processo referenciado"""
                nProc: Annotated[str, Element] = None
                indProc: Annotated[str, Element] = None

            procRef: Annotated[ElementList[_procRef], Element] = None

        infAdic: Annotated[_infAdic, Element] = None

        class _exporta(ComplexType):
            """Informações de exportação"""
            UFSaidaPais: Annotated[TUfEmi, Element] = None
            xLocExporta: Annotated[str, Element] = None
            xLocDespacho: Annotated[str, Element] = None

        exporta: Annotated[_exporta, Element] = None

        class _compra(ComplexType):
            """Informações de compras  (Nota de Empenho, Pedido e Contrato)"""
            xNEmp: Annotated[str, Element] = None
            xPed: Annotated[str, Element] = None
            xCont: Annotated[str, Element] = None

        compra: Annotated[_compra, Element] = None

        class _cana(ComplexType):
            """Informações de registro aquisições de cana"""
            safra: Annotated[str, Element] = None
            ref: Annotated[str, Element] = None

            class _forDia(ComplexType):
                """Fornecimentos diários"""
                dia: Annotated[str, Attribute(pattern=r'[1-9]|[1][0-9]|[2][0-9]|[3][0-1]')] = None
                qtde: Annotated[TDec_1110v, Element] = None

            forDia: Annotated[ElementList[_forDia], Element] = None
            qTotMes: Annotated[TDec_1110v, Element] = None
            qTotAnt: Annotated[TDec_1110v, Element] = None
            qTotGer: Annotated[TDec_1110v, Element] = None

            class _deduc(ComplexType):
                """Deduções - Taxas e Contribuições"""
                xDed: Annotated[str, Element] = None
                vDed: Annotated[TDec_1302, Element] = None

            deduc: Annotated[ElementList[_deduc], Element] = None
            vFor: Annotated[TDec_1302, Element] = None
            vTotDed: Annotated[TDec_1302, Element] = None
            vLiqFor: Annotated[TDec_1302, Element] = None

        cana: Annotated[_cana, Element] = None
        infRespTec: Annotated[TInfRespTec, Element] = None

    infNFe: Annotated[_infNFe, Element] = None

    class _infNFeSupl(ComplexType):
        """Informações suplementares Nota Fiscal"""
        qrCode: Annotated[str, Element] = None
        urlChave: Annotated[str, Element] = None

    infNFeSupl: Annotated[_infNFeSupl, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TProtNFe(ComplexType):
    """Tipo Protocolo de status resultado do processamento da NF-e"""
    versao: Annotated[TVerNFe, Attribute] = None

    class _infProt(ComplexType):
        """Dados do protocolo de status"""
        Id: Annotated[str, Attribute] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        chNFe: Annotated[TChNFe, Element] = None
        dhRecbto: Annotated[TDateTimeUTC, Element] = None
        nProt: Annotated[TProt, Element] = None
        digVal: Annotated[TXML, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None
        cMsg: Annotated[str, Element] = None
        xMsg: Annotated[str, Element] = None

    infProt: Annotated[_infProt, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TIdLote(str):
    """ Tipo Identificação de Lote"""
    pass


class TEnviNFe(ComplexType):
    """ Tipo Pedido de Concessão de Autorização da Nota Fiscal Eletrônica"""
    versao: Annotated[TVerNFe, Attribute] = None
    idLote: Annotated[TIdLote, Element] = None
    indSinc: Annotated[str, Element] = None
    NFe: Annotated[ElementList[TNFe], Element] = None


class TRetEnviNFe(ComplexType):
    """Tipo Retorno do Pedido de Autorização da Nota Fiscal Eletrônica"""
    versao: Annotated[TVerNFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    dhRecbto: Annotated[TDateTimeUTC, Element] = None

    class _infRec(ComplexType):
        """Dados do Recibo do Lote"""
        nRec: Annotated[TRec, Element] = None
        tMed: Annotated[TMed, Element] = None

    infRec: Annotated[_infRec, Element] = None
    protNFe: Annotated[TProtNFe, Element] = None
    infRec_protNFe = Choice("infRec", "protNFe")


class TConsReciNFe(ComplexType):
    """Tipo Pedido de Consulta do Recido do Lote de Notas Fiscais Eletrônicas"""
    versao: Annotated[TVerNFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    nRec: Annotated[TRec, Element] = None


class TRetConsReciNFe(ComplexType):
    """Tipo Retorno do Pedido de  Consulta do Recido do Lote de Notas Fiscais Eletrônicas"""
    versao: Annotated[TVerNFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    nRec: Annotated[TRec, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    dhRecbto: Annotated[TDateTimeUTC, Element] = None
    cMsg: Annotated[str, Element] = None
    xMsg: Annotated[str, Element] = None
    protNFe: Annotated[ElementList[TProtNFe], Element] = None


class TNfeProc(ComplexType):
    """ Tipo da NF-e processada"""
    versao: Annotated[TVerNFe, Attribute] = None
    NFe: Annotated[TNFe, Element] = None
    protNFe: Annotated[TProtNFe, Element] = None


