# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: nfe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteNFe_v400 import *


class NFe(TNFe):
    """Nota Fiscal Eletrônica"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


