# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteNFe_v400 import *


class nfeProc(TNfeProc):
    """NF-e processada"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


