# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procRemIndus_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteRemIndus_v100 import *


class procEventoNFe(TProcEvento):
    """Schema XML de validacao do proc de eventos de remessa para industrializacao"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


