# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procEPEC_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEPEC_v100 import *


class procEventoNFe(TProcEvento):
    """Schema XML de validação do proc Evento de emissão prévia em contingência"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


