# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procInutNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteInutNFe_v400 import *


class ProcInutNFe(TProcInutNFe):
    """Pedido de inutilização de númeração de  NF-e processado"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


