# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procAverbNFe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteAverb_v100 import *


class procEventoNFe(TProcEvento):
    """Schema XML de validação do proc do evento de averbação"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


