# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procCCeNFe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteCCe_v100 import *


class procEventoNFe(TProcEvento):
    """Schema XML de validação do proc Carta de Correção da NFe"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


