# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procEventoNFe_v99.99.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .retEnvCancelPProrrogNFe_v10 import *


class procEventoNFe(ComplexType):
    versao: Annotated[str, Attribute(pattern=r'[0-9]{2}\.[0-9]{2}')] = None

    class _evento(ComplexType):
        envEvento: Annotated[str, Element] = None

    evento: Annotated[_evento, Element] = None

    class _retEvento(ComplexType):
        retEnvEvento: Annotated[str, Element] = None

    retEvento: Annotated[_retEvento, Element] = None


