# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procInutNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteInutNFe_v310 import *


class ProcInutNFe(TProcInutNFe):
    """Pedido de inutilização de númeração de  NF-e processado"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


