# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procEventoCancSubst_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEventoCancSubst_v100 import *


class procEventoNFe(TProcEvento):
    """Schema XML de validação do proc Cancelamento"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


