# Generated by xsd2py.py
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposDistDFe_v101 import *


class TVerResEvento(str):
    """Tipo Versão do leiate resNFe"""
    pass


class resEvento(ComplexType):
    """Schema da estrutura XML gerada pelo Ambiente Nacional com o conjunto de informações resumidas de um evento de NF-e"""
    versao: Annotated[TVerResEvento, Attribute] = None
    cOrgao: Annotated[TCOrgaoIBGE, Element] = None
    CNPJ: Annotated[TCnpj, Element] = None
    CPF: Annotated[TCpf, Element] = None
    CNPJ_CPF = Choice("CNPJ", "CPF")
    chNFe: Annotated[TChNFe, Element] = None
    dhEvento: Annotated[TDateTimeUTC, Element] = None
    tpEvento: Annotated[str, Element] = None
    nSeqEvento: Annotated[str, Element] = None
    xEvento: Annotated[str, Element] = None
    dhRecbto: Annotated[TDateTimeUTC, Element] = None
    nProt: Annotated[TProt, Element] = None

