# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: resEvento_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposDistDFe_v101 import *


TVerResEvento: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do leiate resNFe""", ]


class resEvento(ComplexType):
    """Schema da estrutura XML gerada pelo Ambiente Nacional com o conjunto de informações resumidas de um evento de NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"
    versao: Annotated[TVerResEvento, Attribute] = None
    cOrgao: Annotated[TCOrgaoIBGE, Element] = None
    CNPJ: Annotated[TCnpj, Element] = None
    CPF: Annotated[TCpf, Element] = None
    CNPJ_CPF = Choice("CNPJ", "CPF")
    chNFe: Annotated[TChNFe, Element] = None
    dhEvento: Annotated[datetime | str, Element] = None
    tpEvento: Annotated[str, Element] = None
    nSeqEvento: Annotated[str, Element] = None
    xEvento: Annotated[str, Element] = None
    dhRecbto: Annotated[datetime | str, Element] = None
    nProt: Annotated[TProt, Element] = None


