# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: resNFe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposDistDFe_v100 import *


class TVerResNFe(str):
    """Tipo Versão do leiate resNFe"""
    pass


class resNFe(ComplexType):
    """Schema da estrutura XML gerada pelo Ambiente Nacional com o conjunto de informações resumidas de uma NF-e"""
    versao: Annotated[TVerResNFe, Attribute] = None
    chNFe: Annotated[TChNFe, Element] = None
    CNPJ: Annotated[TCnpj, Element] = None
    CPF: Annotated[TCpf, Element] = None
    CNPJ_CPF = Choice("CNPJ", "CPF")
    xNome: Annotated[str, Element] = None
    IE: Annotated[TIe, Element] = None
    dhEmi: Annotated[TDateTimeUTC, Element] = None
    tpNF: Annotated[str, Element] = None
    vNF: Annotated[TDec_1302, Element] = None
    digVal: Annotated[TXML, Element] = None
    dhRecbto: Annotated[TDateTimeUTC, Element] = None
    nProt: Annotated[TProt, Element] = None
    cSitNFe: Annotated[str, Element] = None


