# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsStatServ_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsStatServ_v400 import *


class retConsStatServ(TRetConsStatServ):
    """Schema XML de validação do Resultado da Consulta do Status do Serviço"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


