# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retconsNFeDest_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteConsNFeDest_v101 import *


class retConsNFeDest(TRetConsNFeDest):
    """Schema XML de validação do retorno de resumo das NF-e encontradas """
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


