# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsReciNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteNFe_v400 import *


class retConsReciNFe(TRetConsReciNFe):
    """Schema XML de validação do retorno do Pedido de  Consulta do Recido do Lote de Notas Fiscais Eletrônicas"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


