# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsSitNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsSitNFe_v400 import *


class retConsSitNFe(TRetConsSitNFe):
    """Schema XML de validação do retorno da consulta da situação atual da NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


