# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsReciNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteNFe_v310 import *


class retConsReciNFe(TRetConsReciNFe):
    """Schema XML de validação do retorno do Pedido de  Consulta do Recido do Lote de Notas Fiscais Eletrônicas"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


