# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retconsNFeDest_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsNFeDest_v101 import *


class retConsNFeDest(TRetConsNFeDest):
    """Schema XML de validação do retorno de resumo das NF-e encontradas """
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


