# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retDownloadNFe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteDownloadNFe_v100 import *


class retDownloadNFe(TRetDownloadNFe):
    """Schema XML de validação do retorno do pedido de download das NF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


