# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEnvEventoCancSubst_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteEventoCancSubst_v100 import *


class retEnvEvento(TRetEnvEvento):
    """Schema XML de Retorno da envio do Evento Cancelamento"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


