# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEnviNFe_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteNFe_v310 import *


class retEnviNFe(TRetEnviNFe):
    """Schema XML de validação do retorno do Pedido de Concessão de Autorização da Nota Fiscal Eletrônica"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


