# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEnvSuframaInternaliza_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteSuframaInternaliza_v100 import *


class retEnvEvento(TRetEnvEvento):
    """Schema XML de Retorno da envio do evento do Internalizacao SUFRAMA 990910"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


