# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEnvRemIndus_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteRemIndus_v100 import *


class retEnvEvento(TRetEnvEvento):
    """Schema XML de Retorno do envio de evento de pedido de prorrogacao de remessa para industrializacao"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


