# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEnvSuframaVistoria_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteSuframaVistoria_v100 import *


class retEnvEvento(TRetEnvEvento):
    """Schema XML de Retorno da envio do evento do Vistoria SUFRAMA 990900"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


