# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retInutNFe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteInutNFe_v400 import *


class retInutNFe(TRetInutNFe):
    """Schema XML de validação do retorno do Pedido de Inutilização de Numeração da Nota Fiscal Eletrônica"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


