# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: tiposDistDFe_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature


TNSU: TypeAlias = Annotated[str, SimpleType, """Tipo número sequencial único""", ]


TQNSU: TypeAlias = Annotated[int, SimpleType, """Tipo quantidade de NSU""", ]


TVerDistDFe: TypeAlias = Annotated[str, SimpleType, """Tipo Versão dos leiautes do Web Service NFeDistribuicaoDFe""", ]


TAmb: TypeAlias = Annotated[str, SimpleType, """Tipo Ambiente""", ]


TCodUfIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código da UF da tabela do IBGE""", ]


TCOrgaoIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código de orgão (UF da tabela do IBGE + 90 RFB)""", ]


TCnpj: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CNPJ""", ]


TCpf: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CPF""", ]


TString: TypeAlias = Annotated[str, SimpleType, """ Tipo string genérico""", ]


TVerAplic: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do Aplicativo""", ]


TStat: TypeAlias = Annotated[str, SimpleType, """Tipo Código da Mensagem enviada""", ]


TMotivo: TypeAlias = Annotated[str, SimpleType, """Tipo Motivo""", ]


TChNFe: TypeAlias = Annotated[str, SimpleType, """Tipo Chave da Nota Fiscal Eletrônica""", ]


TProt: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Protocolo de Status""", ]


TDateTimeUTC: TypeAlias = Annotated[str, SimpleType, """Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)""", ]


TIe: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do Emitente // alterado EM 24/10/08 para aceitar ISENTO""", ]


TDec_1302: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais""", (13, 2)]


