# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: tiposBasico_v1.03.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature


class TCodUfIBGE(str):
    """Tipo Código da UF da tabela do IBGE"""
    pass


class TCodMunIBGE(str):
    """Tipo Código do Município da tabela do IBGE"""
    pass


class TChNFe(str):
    """Tipo Chave da Nota Fiscal Eletrônica"""
    pass


class TProt(str):
    """Tipo Número do Protocolo de Status"""
    pass


class TRec(str):
    """Tipo Número do Recibo do envio de lote de NF-e"""
    pass


class TStat(str):
    """Tipo Código da Mensagem enviada"""
    pass


class TCnpj(str):
    """Tipo Número do CNPJ"""
    pass


class TCnpjVar(str):
    """Tipo Número do CNPJ tmanho varíavel (3-14)"""
    pass


class TCnpjOpc(str):
    """Tipo Número do CNPJ Opcional"""
    pass


class TCpf(str):
    """Tipo Número do CPF"""
    pass


class TCpfVar(str):
    """Tipo Número do CPF de tamanho variável (3-11)"""
    pass


class TDec_0302(Decimal):
    """Tipo Decimal com 5 dígitos, sendo 3 de corpo e 2 decimais"""
    _xs_dec = (3, 2)
    _xs_optional = False


class TDec_0302Opc(Decimal):
    """Tipo Decimal com 5 dígitos, sendo 3 de corpo e 2 decimais, utilizado em tags opcionais"""
    _xs_dec = (3, 2)
    _xs_optional = True


class TDec_0803(Decimal):
    """Tipo Decimal com 11 dígitos, sendo 8 de corpo e 3 decimais"""
    _xs_dec = (8, 3)
    _xs_optional = False


class TDec_0803Opc(Decimal):
    """Tipo Decimal com 11 dígitos, sendo 8 de corpo e 3 decimais utilizado em tags opcionais"""
    _xs_dec = (8, 3)
    _xs_optional = True


class TDec_0804(Decimal):
    """Tipo Decimal com 12 dígitos, sendo 8 de corpo e 4decimais"""
    _xs_dec = (8, 4)
    _xs_optional = False


class TDec_0804Opc(Decimal):
    """Tipo Decimal com 12 dígitos, sendo 8 de corpo e 4 decimais, utilizado em tags opcionais"""
    _xs_dec = (8, 4)
    _xs_optional = True


class TDec_1104(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 11 de corpo e 4 decimais"""
    _xs_dec = (11, 4)
    _xs_optional = False


class TDec_1104Opc(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 11 de corpo e 4 decimais, utilizado em tags opcionais"""
    _xs_dec = (11, 4)
    _xs_optional = True


class TDec_1203(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 12 de corpo e 3 decimais"""
    _xs_dec = (12, 3)
    _xs_optional = False


class TDec_1203Opc(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 12 de corpo e 3 decimais, utilizado em tags opcionais"""
    _xs_dec = (12, 3)
    _xs_optional = True


class TDec_1204(Decimal):
    """Tipo Decimal com 16 dígitos, sendo 12 de corpo e 4 decimais"""
    _xs_dec = (12, 4)
    _xs_optional = False


class TDec_1204Opc(Decimal):
    """Tipo Decimal com 16 dígitos, sendo 12 de corpo e 4 decimais, utilizado em tags opcionais"""
    _xs_dec = (12, 4)
    _xs_optional = True


class TDec_1302(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais"""
    _xs_dec = (13, 2)
    _xs_optional = False


class TDec_1302Opc(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais"""
    _xs_dec = (13, 2)
    _xs_optional = True


class TDec_1110(Decimal):
    """Tipo Decimal com até  21 dígitos, sendo 11 de corpo e até 10 decimais // aperfeiçoamento v2.0"""
    _xs_dec = (11, 10)
    _xs_optional = False


class TDec_1104v(Decimal):
    """Tipo Decimal com até 15 dígitos, sendo 11 de corpo e até 4 decimais  // aperfeiçoamento v2.0"""
    _xs_dec = (11, 4)
    _xs_optional = False


class TIeDest(str):
    """Tipo Inscrição Estadual do Destinatário // alterado para aceitar vazio ou ISENTO - maio/2010 v2.0"""
    pass


class TIeST(str):
    """Tipo Inscrição Estadual do ST // acrescentado EM 24/10/08"""
    pass


class TIe(str):
    """Tipo Inscrição Estadual do Emitente // alterado EM 24/10/08 para aceitar ISENTO"""
    pass


class TMod(str):
    """Tipo Modelo Documento Fiscal"""
    pass


class TNF(str):
    """Tipo Número do Documento Fiscal"""
    pass


class TSerie(str):
    """Tipo Série do Documento Fiscal """
    pass


class Tpais(str):
    """Tipo Código do Pais 
// PL_005d - 11/08/09
eliminado:
 4235-LEBUAN, ILHAS - 
acrescentado:
7200 SAO TOME E PRINCIPE, ILHAS,
8958 ZONA DO CANAL DO PANAMA               
9903 PROVISAO DE NAVIOS E AERONAVES        
9946 A DESIGNAR                            
9950 BANCOS CENTRAIS                       
9970 ORGANIZACOES INTERNACIONAIS
 // PL_005b - 24/10/08
 // Acrescentado:
 4235 - LEBUAN,ILHAS
 4885 - MAYOTTE (ILHAS FRANCESAS)  
// NT2011/004
 acrescentado a tabela de paises
//PL_006t - 21/03/2014
acrescentado:
5780 - Palestina
7600 - Sudão do Sul 
 """
    pass


class TUf(str):
    """Tipo Sigla da UF"""
    pass


class TUfEmi(str):
    """Tipo Sigla da UF de emissor // acrescentado em 24/10/08 """
    pass


class TAmb(str):
    """Tipo Ambiente"""
    pass


class TVerAplic(TString):
    """Tipo Versão do Aplicativo"""
    pass


class TMotivo(TString):
    """Tipo Motivo"""
    pass


class TJust(TString):
    """Tipo Justificativa"""
    pass


class TServ(TString):
    """Tipo Serviço solicitado"""
    pass


class Tano(str):
    """ Tipo ano"""
    pass


class TMed(str):
    """ Tipo temp médio em segundos"""
    pass


class TString(str):
    """ Tipo string genérico"""
    pass


class TData(str):
    """ Tipo data AAAA-MM-DD"""
    pass


class TTime(str):
    """ Tipo hora HH:MM:SS // tipo acrescentado na v2.0"""
    pass


class TDateTimeUTC(str):
    """Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)"""
    pass


class TPlaca(str):
    pass


class TCOrgaoIBGE(str):
    """Tipo Código de orgão (UF da tabela do IBGE + 90 RFB)"""
    pass


class TLatitude(str):
    """Coordenada geográfica Latitude"""
    pass


class TLongitude(str):
    """Coordenada geográfica Longitude"""
    pass

