# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: tiposBasico_v3.10.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature


TCodUfIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código da UF da tabela do IBGE""", ]


TCodMunIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código do Município da tabela do IBGE""", ]


TChNFe: TypeAlias = Annotated[str, SimpleType, """Tipo Chave da Nota Fiscal Eletrônica""", ]


TProt: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Protocolo de Status""", ]


TRec: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Recibo do envio de lote de NF-e""", ]


TStat: TypeAlias = Annotated[str, SimpleType, """Tipo Código da Mensagem enviada""", ]


TCnpj: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CNPJ""", ]


TCnpjVar: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CNPJ tmanho varíavel (3-14)""", ]


TCnpjOpc: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CNPJ Opcional""", ]


TCpf: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CPF""", ]


TCpfVar: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CPF de tamanho variável (3-11)""", ]


TDec_0204v: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com até 2 dígitos inteiros, podendo ter de 1 até 4 decimais""", (2, 4)]


TDec_0302a04: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais""", (3, 4)]


TDec_0302a04Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com até 3 dígitos inteiros e 2 até 4 decimais. Utilizados em TAGs opcionais, não aceita valor zero.""", (3, 4, True)]


TDec_0302Max100: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 3 inteiros (no máximo 100), com 2 decimais""", (3, 2)]


TDec_0302a04Max100: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 3 inteiros (no máximo 100), com até 4 decimais""", (3, 4)]


TDec_0803v: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 8 inteiros, podendo ter de 1 até 3 decimais""", (8, 3)]


TDec_1104: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 inteiros, podendo ter 4 decimais""", (11, 4)]


TDec_1104v: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 inteiros, podendo ter de 1 até 4 decimais""", (11, 4)]


TDec_1104Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 inteiros, podendo ter 4 decimais (utilizado em tags opcionais)""", (11, 4, True)]


TDec_1110v: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 inteiros, podendo ter de 1 até 10 decimais""", (11, 10)]


TDec_1203: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 inteiros, podendo ter  3 decimais""", (12, 3)]


TDec_1204: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 inteiros e 4 decimais""", (12, 4)]


TDec_1204v: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 inteiros de 1 até 4 decimais""", (12, 4)]


TDec_1204Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 inteiros com 1 até 4 decimais""", (12, 4, True)]


TDec_1204temperatura: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 inteiros, 1 a 4 decimais""", (12, 4)]


TDec_1302: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais""", (13, 2)]


TDec_1302Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais""", (13, 2, True)]


TIeDest: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do Destinatário // alterado para aceitar vazio ou ISENTO - maio/2010 v2.0""", ]


TIeDestNaoIsento: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do Destinatário // alterado para aceitar vazio ou ISENTO - maio/2010 v2.0""", ]


TIeST: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do ST // acrescentado EM 24/10/08""", ]


TIe: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do Emitente // alterado EM 24/10/08 para aceitar ISENTO""", ]


TMod: TypeAlias = Annotated[str, SimpleType, """Tipo Modelo Documento Fiscal""", ]


TNF: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Documento Fiscal""", ]


TSerie: TypeAlias = Annotated[str, SimpleType, """Tipo Série do Documento Fiscal """, ]


TUf: TypeAlias = Annotated[str, SimpleType, """Tipo Sigla da UF""", ]


TUfEmi: TypeAlias = Annotated[str, SimpleType, """Tipo Sigla da UF de emissor // acrescentado em 24/10/08 """, ]


TAmb: TypeAlias = Annotated[str, SimpleType, """Tipo Ambiente""", ]


TVerAplic: TypeAlias = Annotated[TString, SimpleType, """Tipo Versão do Aplicativo""", ]


TMotivo: TypeAlias = Annotated[TString, SimpleType, """Tipo Motivo""", ]


TJust: TypeAlias = Annotated[TString, SimpleType, """Tipo Justificativa""", ]


TServ: TypeAlias = Annotated[TString, SimpleType, """Tipo Serviço solicitado""", ]


Tano: TypeAlias = Annotated[str, SimpleType, """ Tipo ano""", ]


TMed: TypeAlias = Annotated[str, SimpleType, """ Tipo temp médio em segundos""", ]


TString: TypeAlias = Annotated[str, SimpleType, """ Tipo string genérico""", ]


TData: TypeAlias = Annotated[str, SimpleType, """ Tipo data AAAA-MM-DD""", ]


TTime: TypeAlias = Annotated[str, SimpleType, """ Tipo hora HH:MM:SS // tipo acrescentado na v2.0""", ]


TDateTimeUTC: TypeAlias = Annotated[str, SimpleType, """Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)""", ]


TPlaca: TypeAlias = Annotated[str, SimpleType, ]


TCOrgaoIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código de orgão (UF da tabela do IBGE + 90 RFB)""", ]


