# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cancCTeTiposBasico_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .tiposGeralCTe_v200 import *


class TVerCancCTe(str):
    """ Tipo Versão de cancela CT-e - 1.04"""
    pass


class TCancCTe(ComplexType):
    """Tipo Pedido de Cancelamento de CT-e"""
    versao: Annotated[TVerCancCTe, Attribute] = None

    class _infCanc(ComplexType):
        """Dados do Pedido de Cancelamentode Conhecimento de Transporte Eletrônico"""
        Id: Annotated[str, Attribute(pattern=r'ID[0-9]{44}')] = None
        tpAmb: Annotated[TAmb, Element] = None
        xServ: Annotated[TServ, Element] = None
        chCTe: Annotated[TChNFe, Element] = None
        nProt: Annotated[TProt, Element] = None
        xJust: Annotated[TJust, Element] = None

    infCanc: Annotated[_infCanc, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TRetCancCTe(ComplexType):
    """Tipo retorno Pedido de Cancelamento CT-e"""
    versao: Annotated[TVerCancCTe, Attribute] = None

    class _infCanc(ComplexType):
        """Dados do Resultado do Pedido de Cancelamento do Conhecimento de Transporte Eletrônico"""
        Id: Annotated[str, Attribute] = None
        tpAmb: Annotated[TAmb, Element] = None
        cUF: Annotated[TCodUfIBGE, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None
        chCTe: Annotated[TChNFe, Element] = None
        dhRecbto: Annotated[datetime, Element] = None
        nProt: Annotated[TProt, Element] = None

    infCanc: Annotated[_infCanc, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TProcCancCTe(ComplexType):
    """Tipo Pedido de Cancelamento de CT-e processado"""
    versao: Annotated[TVerCancCTe, Attribute] = None
    cancCTe: Annotated[TCancCTe, Element] = None
    retCancCTe: Annotated[TRetCancCTe, Element] = None


