# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consReciCTeTiposBasico_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposGeralCTe_v200 import *


TVerConsReciCTe: TypeAlias = Annotated[str, SimpleType, """ Tipo Versão do Consulta Lote de CT-e - 1.04""", ]


class TProtCTe(ComplexType):
    """Tipo Protocolo de status resultado do processamento da CT-e"""
    versao: Annotated[TVerConsReciCTe, Attribute] = None

    class _infProt(ComplexType):
        """Dados do protocolo de status"""
        Id: Annotated[str, Attribute] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        chCTe: Annotated[TChNFe, Element] = None
        dhRecbto: Annotated[datetime | str, Element] = None
        nProt: Annotated[TProt, Element] = None
        digVal: Annotated[TXML, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None

    infProt: Annotated[_infProt, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TConsReciCTe(ComplexType):
    """Tipo Pedido de Consulta do Recibo do Lote de CT-e"""
    versao: Annotated[TVerConsReciCTe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    nRec: Annotated[TRec, Element] = None


class TRetConsReciCTe(ComplexType):
    """Tipo Retorno do Pedido de  Consulta do Recibo do Lote de CT-e"""
    versao: Annotated[TVerConsReciCTe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    nRec: Annotated[TRec, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    protCTe: Annotated[ElementList[TProtCTe], Element] = None


