# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consCad_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsultaCadastro_v200 import *


class ConsCad(TConsCad):
    """Schema XML de validação do retorno da consulta cadastro contribuintes"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


