# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consSitCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .consSitCTeTiposBasico_v400 import *


class consSitCTe(TConsSitCTe):
    """Schema de validação XML dp Pedido de Consulta da Situação Atual do CT-e."""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


