# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consReciCTeTiposBasico_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposGeralCTe_v300 import *
from .cteTiposBasico_v300 import *


class TVerConsReciCTe(str):
    """ Tipo Versão do Consulta Lote de CT-e """
    pass


class TConsReciCTe(ComplexType):
    """Tipo Pedido de Consulta do Recibo do Lote de CT-e"""
    versao: Annotated[TVerConsReciCTe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    nRec: Annotated[TRec, Element] = None


class TRetConsReciCTe(ComplexType):
    """Tipo Retorno do Pedido de  Consulta do Recibo do Lote de CT-e"""
    versao: Annotated[TVerConsReciCTe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    nRec: Annotated[TRec, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    protCTe: Annotated[ElementList[TProtCTe], Element] = None

