# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consReciCTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .consReciCTeTiposBasico_v300 import *


class consReciCTe(TConsReciCTe):
    """Schema XML de validação do Pedido de Consulta de Lote de CT-e"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


