# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consStatServCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .consStatServTiposBasico_v400 import *


class consStatServCTe(TConsStatServ):
    """Schema XML de validação do Pedido de Consulta do Status do Serviço CT-e"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


