# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cte_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v200 import *


class CTe(TCTe):
    """Conhecimento de Transporte Eletrônico"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


