# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cteModalRodoviario_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v400 import *


class rodo(ComplexType):
    """Informações do modal Rodoviário"""
    RNTRC: Annotated[TRNTRC, Element] = None

    class _occ(ComplexType):
        """Ordens de Coleta associados"""
        serie: Annotated[str, Element] = None
        nOcc: Annotated[str, Element] = None
        dEmi: Annotated[TData, Element] = None

        class _emiOcc(ComplexType):
            CNPJ: Annotated[TCnpj, Element] = None
            cInt: Annotated[str, Element] = None
            IE: Annotated[TIe, Element] = None
            UF: Annotated[TUf, Element] = None
            fone: Annotated[TFone, Element] = None

        emiOcc: Annotated[_emiOcc, Element] = None

    occ: Annotated[ElementList[_occ], Element] = None


