# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cteModalAquaviario_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .cteTiposBasico_v400 import *


class aquav(ComplexType):
    """Informações do modal Aquaviário"""
    vPrest: Annotated[TDec_1302, Element] = None
    vAFRMM: Annotated[TDec_1302, Element] = None
    xNavio: Annotated[str, Element] = None

    class _balsa(ComplexType):
        """Grupo de informações das balsas"""
        xBalsa: Annotated[str, Element] = None

    balsa: Annotated[ElementList[_balsa], Element] = None
    nViag: Annotated[str, Element] = None
    direc: Annotated[str, Element] = None
    irin: Annotated[str, Element] = None

    class _detCont(ComplexType):
        """Grupo de informações de detalhamento dos conteiners 
(Somente para Redespacho Intermediário e Serviço Vinculado a Multimodal)"""
        nCont: Annotated[TContainer, Element] = None

        class _lacre(ComplexType):
            """Grupo de informações dos lacres dos cointainers da qtde da carga """
            nLacre: Annotated[str, Element] = None

        lacre: Annotated[ElementList[_lacre], Element] = None

        class _infDoc(ComplexType):
            """Informações dos documentos dos conteiners"""

            class _infNF(ComplexType):
                """Informações das NF"""
                serie: Annotated[str, Element] = None
                nDoc: Annotated[str, Element] = None
                unidRat: Annotated[TDec_0302_0303, Element] = None

            infNF: Annotated[ElementList[_infNF], Element] = None

            class _infNFe(ComplexType):
                """Informações das NFe"""
                chave: Annotated[TChDFe, Element] = None
                unidRat: Annotated[TDec_0302_0303, Element] = None

            infNFe: Annotated[ElementList[_infNFe], Element] = None
            infNF_infNFe = Choice("infNF", "infNFe")

        infDoc: Annotated[_infDoc, Element] = None

    detCont: Annotated[ElementList[_detCont], Element] = None
    tpNav: Annotated[str, Element] = None


