# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cteModalDutoviario_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v200 import *


class duto(ComplexType):
    """Informações do modal Dutoviário"""
    vTar: Annotated[TDec_0906Opc, Element] = None
    dIni: Annotated[TData, Element] = None
    dFim: Annotated[TData, Element] = None


