# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cteMultiModal_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v300 import *


class multimodal(ComplexType):
    """Informações do Multimodal"""
    COTM: Annotated[str, Element] = None
    indNegociavel: Annotated[str, Element] = None

    class _seg(ComplexType):
        """Informações de Seguro do Multimodal"""

        class _infSeg(ComplexType):
            """Informações da seguradora"""
            xSeg: Annotated[str, Element] = None
            CNPJ: Annotated[TCnpjOpc, Element] = None

        infSeg: Annotated[_infSeg, Element] = None
        nApol: Annotated[str, Element] = None
        nAver: Annotated[str, Element] = None

    seg: Annotated[_seg, Element] = None


