# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cteMultiModal_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v200 import *


class multimodal(ComplexType):
    """Informações do Multimodal"""
    COTM: Annotated[str, Element] = None
    indNegociavel: Annotated[str, Element] = None


