# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: cteModalRodoviario_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposGeralCTe_v400 import *
from .cteTiposBasico_v400 import *


class rodo(ComplexType):
    """Informações do modal Rodoviário"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"
    RNTRC: Annotated[TRNTRC, Element] = None

    class _occ(ComplexType):
        """Ordens de Coleta associados"""
        serie: Annotated[str, Element] = None
        nOcc: Annotated[str, Element] = None
        dEmi: Annotated[TData, Element] = None

        class _emiOcc(ComplexType):
            CNPJ: Annotated[TCnpj, Element] = None
            cInt: Annotated[str, Element] = None
            IE: Annotated[TIe, Element] = None
            UF: Annotated[TUf, Element] = None
            fone: Annotated[TFone, Element] = None

        emiOcc: Annotated[_emiOcc, Element] = None

    occ: Annotated[ElementList[_occ], Element] = None


