# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: DFeTiposBasicos_v1.00.xsd
# xmlns: None
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature


TStringRTC: TypeAlias = Annotated[str, SimpleType, """ Tipo string genérico""", ]


TCST: TypeAlias = Annotated[str, SimpleType, """Código Situação Tributária do IBS/CBS""", ]


TcClassTrib: TypeAlias = Annotated[str, SimpleType, """Código de Classificação Tributária do IBS e da CBS""", ]


TcCredPres: TypeAlias = Annotated[str, SimpleType, """Código de Classificação do Crédito Presumido do IBS e da CBS, conforme tabela cCredPres""", ]


TDec1104RTC: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 11 de corpo e 4 decimais""", (11, 4)]


TDec_1104OpRTC: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 inteiros, podendo ter 4 decimais (utilizado em tags opcionais)""", (11, 4)]


TDec1302RTC: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais""", (13, 2)]


TDec_0302_04RTC: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com até 3 dígitos inteiros, podendo ter de 2 até 4 decimais""", (3, 2)]


TOperCompraGov: TypeAlias = Annotated[str, SimpleType, """Tipo da Operação com Ente Governamental""", ]


TEnteGov: TypeAlias = Annotated[str, SimpleType, """Tipo de Ente Governamental""", ]


TTpCredPresIBSZFM: TypeAlias = Annotated[str, SimpleType, """Tipo de classificação do Crédito Presumido IBS ZFM""", ]


TIndDoacao: TypeAlias = Annotated[str, SimpleType, """Tipo Indicador de Doação""", ]


class TRed(ComplexType):
    """Tipo Redução Base de Cálculo"""
    pRedAliq: Annotated[TDec_0302_04RTC, Element] = None
    pAliqEfet: Annotated[TDec_0302_04RTC, Element] = None


class TDif(ComplexType):
    """Tipo Diferimento"""
    pDif: Annotated[TDec_0302_04RTC, Element] = None
    vDif: Annotated[TDec1302RTC, Element] = None


class TDevTrib(ComplexType):
    """Tipo Devolução Tributo"""
    vDevTrib: Annotated[TDec1302RTC, Element] = None


class TTribRegular(ComplexType):
    """Tipo Tributação Regular"""
    CSTReg: Annotated[TCST, Element] = None
    cClassTribReg: Annotated[TcClassTrib, Element] = None
    pAliqEfetRegIBSUF: Annotated[TDec_0302_04RTC, Element] = None
    vTribRegIBSUF: Annotated[TDec1302RTC, Element] = None
    pAliqEfetRegIBSMun: Annotated[TDec_0302_04RTC, Element] = None
    vTribRegIBSMun: Annotated[TDec1302RTC, Element] = None
    pAliqEfetRegCBS: Annotated[TDec_0302_04RTC, Element] = None
    vTribRegCBS: Annotated[TDec1302RTC, Element] = None


class TTribCompraGov(ComplexType):
    """Tipo Tributação Compra Governamental"""
    pAliqIBSUF: Annotated[TDec_0302_04RTC, Element] = None
    vTribIBSUF: Annotated[TDec1302RTC, Element] = None
    pAliqIBSMun: Annotated[TDec_0302_04RTC, Element] = None
    vTribIBSMun: Annotated[TDec1302RTC, Element] = None
    pAliqCBS: Annotated[TDec_0302_04RTC, Element] = None
    vTribCBS: Annotated[TDec1302RTC, Element] = None


class TCIBS(ComplexType):
    """Tipo CBS IBS Completo"""
    vBC: Annotated[TDec1302RTC, Element] = None

    class _gIBSUF(ComplexType):
        """Grupo de informações do IBS na UF"""
        pIBSUF: Annotated[TDec_0302_04RTC, Element] = None
        gDif: Annotated[TDif, Element] = None
        gDevTrib: Annotated[TDevTrib, Element] = None
        gRed: Annotated[TRed, Element] = None
        vIBSUF: Annotated[TDec1302RTC, Element] = None

    gIBSUF: Annotated[_gIBSUF, Element] = None

    class _gIBSMun(ComplexType):
        """Grupo de Informações do IBS no Município"""
        pIBSMun: Annotated[TDec_0302_04RTC, Element] = None
        gDif: Annotated[TDif, Element] = None
        gDevTrib: Annotated[TDevTrib, Element] = None
        gRed: Annotated[TRed, Element] = None
        vIBSMun: Annotated[TDec1302RTC, Element] = None

    gIBSMun: Annotated[_gIBSMun, Element] = None
    vIBS: Annotated[TDec1302RTC, Element] = None

    class _gCBS(ComplexType):
        """Grupo de Tributação da CBS"""
        pCBS: Annotated[TDec_0302_04RTC, Element] = None
        gDif: Annotated[TDif, Element] = None
        gDevTrib: Annotated[TDevTrib, Element] = None
        gRed: Annotated[TRed, Element] = None
        vCBS: Annotated[TDec1302RTC, Element] = None

    gCBS: Annotated[_gCBS, Element] = None
    gTribRegular: Annotated[TTribRegular, Element] = None
    gTribCompraGov: Annotated[TTribCompraGov, Element] = None


class TEstornoCred(ComplexType):
    """Tipo Estorno de Crédito"""
    vIBSEstCred: Annotated[TDec1302RTC, Element] = None
    vCBSEstCred: Annotated[TDec1302RTC, Element] = None


class TTribNFCom(ComplexType):
    """Grupo de informações da Tributação da NFCom"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gEstornoCred: Annotated[TEstornoCred, Element] = None


class TTribNF3e(ComplexType):
    """Grupo de informações da Tributação da NF3e"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gEstornoCred: Annotated[TEstornoCred, Element] = None


class TTribNFAg(ComplexType):
    """Grupo de informações da Tributação da NFAg"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gEstornoCred: Annotated[TEstornoCred, Element] = None


class TTribCTe(ComplexType):
    """Grupo de informações da Tributação do CTe"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gEstornoCred: Annotated[TEstornoCred, Element] = None


class TTribBPe(ComplexType):
    """Grupo de informações da Tributação do BPe"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gEstornoCred: Annotated[TEstornoCred, Element] = None


class TMonofasia(ComplexType):
    """Tipo Monofasia"""

    class _gMonoPadrao(ComplexType):
        """Grupo de informações da Tributação Monofásica padrão"""
        qBCMono: Annotated[TDec1104RTC, Element] = None
        adRemIBS: Annotated[TDec_0302_04RTC, Element] = None
        adRemCBS: Annotated[TDec_0302_04RTC, Element] = None
        vIBSMono: Annotated[TDec1302RTC, Element] = None
        vCBSMono: Annotated[TDec1302RTC, Element] = None

    gMonoPadrao: Annotated[_gMonoPadrao, Element] = None

    class _gMonoReten(ComplexType):
        """Grupo de informações da Tributação Monofásica sujeita a retenção"""
        qBCMonoReten: Annotated[TDec1104RTC, Element] = None
        adRemIBSReten: Annotated[TDec_0302_04RTC, Element] = None
        vIBSMonoReten: Annotated[TDec1302RTC, Element] = None
        adRemCBSReten: Annotated[TDec_0302_04RTC, Element] = None
        vCBSMonoReten: Annotated[TDec1302RTC, Element] = None

    gMonoReten: Annotated[_gMonoReten, Element] = None

    class _gMonoRet(ComplexType):
        """Grupo de informações da Tributação Monofásica retida anteriormente"""
        qBCMonoRet: Annotated[TDec1104RTC, Element] = None
        adRemIBSRet: Annotated[TDec_0302_04RTC, Element] = None
        vIBSMonoRet: Annotated[TDec1302RTC, Element] = None
        adRemCBSRet: Annotated[TDec_0302_04RTC, Element] = None
        vCBSMonoRet: Annotated[TDec1302RTC, Element] = None

    gMonoRet: Annotated[_gMonoRet, Element] = None

    class _gMonoDif(ComplexType):
        """Grupo de informações do diferimento da Tributação Monofásica"""
        pDifIBS: Annotated[TDec_0302_04RTC, Element] = None
        vIBSMonoDif: Annotated[TDec1302RTC, Element] = None
        pDifCBS: Annotated[TDec_0302_04RTC, Element] = None
        vCBSMonoDif: Annotated[TDec1302RTC, Element] = None

    gMonoDif: Annotated[_gMonoDif, Element] = None
    vTotIBSMonoItem: Annotated[TDec1302RTC, Element] = None
    vTotCBSMonoItem: Annotated[TDec1302RTC, Element] = None


class TTribNFCe(ComplexType):
    """Grupo de informações da Tributação da NFCe"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gIBSCBSMono: Annotated[TMonofasia, Element] = None
    gIBSCBS_gIBSCBSMono = Choice("gIBSCBS", "gIBSCBSMono")


class TTransfCred(ComplexType):
    """Tipo Transferência de Crédito"""
    vIBS: Annotated[TDec1302RTC, Element] = None
    vCBS: Annotated[TDec1302RTC, Element] = None


TCompetApur: TypeAlias = Annotated[str, SimpleType, """Ano e mês referência do período de apuração (AAAA-MM)""", ]


class TAjusteCompet(ComplexType):
    """Tipo Ajuste de Competência"""
    competApur: Annotated[TCompetApur, Element] = None
    vIBS: Annotated[TDec1302RTC, Element] = None
    vCBS: Annotated[TDec1302RTC, Element] = None


class TCredPres(ComplexType):
    """Tipo Crédito Presumido"""
    pCredPres: Annotated[TDec_0302_04RTC, Element] = None
    vCredPres: Annotated[TDec1302RTC, Element] = None
    vCredPresCondSus: Annotated[TDec1302RTC, Element] = None
    vCredPres_vCredPresCondSus = Choice("vCredPres", "vCredPresCondSus")


class TCredPresOper(ComplexType):
    """Tipo Crédito Presumido da Operação"""
    vBCCredPres: Annotated[TDec1302RTC, Element] = None
    cCredPres: Annotated[TcCredPres, Element] = None
    gIBSCredPres: Annotated[TCredPres, Element] = None
    gCBSCredPres: Annotated[TCredPres, Element] = None


class TCredPresIBSZFM(ComplexType):
    """Tipo Informações do crédito presumido de IBS para fornecimentos a partir da ZFM"""
    competApur: Annotated[TCompetApur, Element] = None
    tpCredPresIBSZFM: Annotated[TTpCredPresIBSZFM, Element] = None
    vCredPresIBSZFM: Annotated[TDec1302RTC, Element] = None


class TTribNFe(ComplexType):
    """Grupo de informações da Tributação da NFe"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gIBSCBSMono: Annotated[TMonofasia, Element] = None
    gTransfCred: Annotated[TTransfCred, Element] = None
    gAjusteCompet: Annotated[TAjusteCompet, Element] = None
    gIBSCBS_gIBSCBSMono_gTransfCred_gAjusteCompet = Choice("gIBSCBS", "gIBSCBSMono", "gTransfCred", "gAjusteCompet")
    gEstornoCred: Annotated[TEstornoCred, Element] = None
    gCredPresOper: Annotated[TCredPresOper, Element] = None
    gCredPresIBSZFM: Annotated[TCredPresIBSZFM, Element] = None
    gCredPresOper_gCredPresIBSZFM = Choice("gCredPresOper", "gCredPresIBSZFM")


class TTribNFGas(ComplexType):
    """Grupo de informações da Tributação da NFGas"""
    CST: Annotated[TCST, Element] = None
    cClassTrib: Annotated[TcClassTrib, Element] = None
    indDoacao: Annotated[TIndDoacao, Element] = None
    gIBSCBS: Annotated[TCIBS, Element] = None
    gIBSCBSMono: Annotated[TMonofasia, Element] = None
    gIBSCBS_gIBSCBSMono = Choice("gIBSCBS", "gIBSCBSMono")
    gEstornoCred: Annotated[TEstornoCred, Element] = None


class TIS(ComplexType):
    """Grupo de informações do Imposto Seletivo"""
    CSTIS: Annotated[TCST, Element] = None
    cClassTribIS: Annotated[TcClassTrib, Element] = None
    vBCIS: Annotated[TDec1302RTC, Element] = None
    pIS: Annotated[TDec_0302_04RTC, Element] = None
    pISEspec: Annotated[TDec_0302_04RTC, Element] = None
    uTrib: Annotated[TStringRTC, Element] = None
    qTrib: Annotated[TDec_1104OpRTC, Element] = None
    vIS: Annotated[TDec1302RTC, Element] = None


class TISTot(ComplexType):
    """Grupo de informações de totais do Imposto Seletivo"""
    vIS: Annotated[TDec1302RTC, Element] = None


class TIBSCBSTot(ComplexType):
    """Grupo de informações de totais da CBS/IBS"""
    vBCIBSCBS: Annotated[TDec1302RTC, Element] = None

    class _gIBS(ComplexType):
        """Totalização do IBS"""

        class _gIBSUF(ComplexType):
            """Totalização do IBS de competência da UF"""
            vDif: Annotated[TDec1302RTC, Element] = None
            vDevTrib: Annotated[TDec1302RTC, Element] = None
            vIBSUF: Annotated[TDec1302RTC, Element] = None

        gIBSUF: Annotated[_gIBSUF, Element] = None

        class _gIBSMun(ComplexType):
            """Totalização do IBS de competência Municipal"""
            vDif: Annotated[TDec1302RTC, Element] = None
            vDevTrib: Annotated[TDec1302RTC, Element] = None
            vIBSMun: Annotated[TDec1302RTC, Element] = None

        gIBSMun: Annotated[_gIBSMun, Element] = None
        vIBS: Annotated[TDec1302RTC, Element] = None

    gIBS: Annotated[_gIBS, Element] = None

    class _gCBS(ComplexType):
        """Totalização da CBS"""
        vDif: Annotated[TDec1302RTC, Element] = None
        vDevTrib: Annotated[TDec1302RTC, Element] = None
        vCBS: Annotated[TDec1302RTC, Element] = None

    gCBS: Annotated[_gCBS, Element] = None

    class _gEstornoCred(ComplexType):
        """Totalização do estorno de crédito"""
        vIBSEstCred: Annotated[TDec1302RTC, Element] = None
        vCBSEstCred: Annotated[TDec1302RTC, Element] = None

    gEstornoCred: Annotated[_gEstornoCred, Element] = None


class TIBSCBSMonoTot(ComplexType):
    """Grupo de informações de totais da CBS/IBS com monofasia"""
    vBCIBSCBS: Annotated[TDec1302RTC, Element] = None

    class _gIBS(ComplexType):
        """Totalização do IBS"""

        class _gIBSUF(ComplexType):
            """Totalização do IBS de competência da UF"""
            vDif: Annotated[TDec1302RTC, Element] = None
            vDevTrib: Annotated[TDec1302RTC, Element] = None
            vIBSUF: Annotated[TDec1302RTC, Element] = None

        gIBSUF: Annotated[_gIBSUF, Element] = None

        class _gIBSMun(ComplexType):
            """Totalização do IBS de competência Municipal"""
            vDif: Annotated[TDec1302RTC, Element] = None
            vDevTrib: Annotated[TDec1302RTC, Element] = None
            vIBSMun: Annotated[TDec1302RTC, Element] = None

        gIBSMun: Annotated[_gIBSMun, Element] = None
        vIBS: Annotated[TDec1302RTC, Element] = None
        vCredPres: Annotated[TDec1302RTC, Element] = None
        vCredPresCondSus: Annotated[TDec1302RTC, Element] = None

    gIBS: Annotated[_gIBS, Element] = None

    class _gCBS(ComplexType):
        """Totalização da CBS"""
        vDif: Annotated[TDec1302RTC, Element] = None
        vDevTrib: Annotated[TDec1302RTC, Element] = None
        vCBS: Annotated[TDec1302RTC, Element] = None
        vCredPres: Annotated[TDec1302RTC, Element] = None
        vCredPresCondSus: Annotated[TDec1302RTC, Element] = None

    gCBS: Annotated[_gCBS, Element] = None

    class _gMono(ComplexType):
        """Totais da Monofasia
Só deverá ser utilizado para DFe modelos 55 e 65"""
        vIBSMono: Annotated[TDec1302RTC, Element] = None
        vCBSMono: Annotated[TDec1302RTC, Element] = None
        vIBSMonoReten: Annotated[TDec1302RTC, Element] = None
        vCBSMonoReten: Annotated[TDec1302RTC, Element] = None
        vIBSMonoRet: Annotated[TDec1302RTC, Element] = None
        vCBSMonoRet: Annotated[TDec1302RTC, Element] = None

    gMono: Annotated[_gMono, Element] = None

    class _gEstornoCred(ComplexType):
        """Totalização do estorno de crédito"""
        vIBSEstCred: Annotated[TDec1302RTC, Element] = None
        vCBSEstCred: Annotated[TDec1302RTC, Element] = None

    gEstornoCred: Annotated[_gEstornoCred, Element] = None


class TCompraGovReduzido(ComplexType):
    """Tipo Compras Governamentais
Cada DFe que utilizar deverá utilizar esses tipo no grupo ide"""
    tpEnteGov: Annotated[TEnteGov, Element] = None
    pRedutor: Annotated[TDec_0302_04RTC, Element] = None


class TCompraGov(ComplexType):
    """Tipo Compras Governamentais
Cada DFe que utilizar deverá utilizar esses tipo no grupo ide"""
    tpEnteGov: Annotated[TEnteGov, Element] = None
    pRedutor: Annotated[TDec_0302_04RTC, Element] = None
    tpOperGov: Annotated[TOperCompraGov, Element] = None


