# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: enviCTe_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v200 import *


class enviCTe(TEnviCTe):
    """Schema XML de validação do Envio de Lote CT-e para concessão de autorização"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


