# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCancIECTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v400 import *


class evCancIECTe(ComplexType):
    """Schema XML de validação do evento cancelamento do insucesso de entrega eletrônico do CT-e 
110191"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    nProtIE: Annotated[TProt, Element] = None


