# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCancCECTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v400 import *


class evCancCECTe(ComplexType):
    """Schema XML de validação do evento cancelamento do comprovante de entrega eletrônico do CT-e 
110181"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    nProtCE: Annotated[TProt, Element] = None


