# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCancPrestDesacordo_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v400 import *


class evCancPrestDesacordo(ComplexType):
    """Schema XML de validação do evento Cancelamento Prestação do Serviço em Desacordo 610111"""
    descEvento: Annotated[str, Element] = None
    nProtEvPrestDes: Annotated[TProt, Element] = None


