# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCancCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v400 import *


class evCancCTe(ComplexType):
    """Schema XML de validação do evento do cancelamento 
110111"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    xJust: Annotated[TJust, Element] = None


