# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCancIECTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoCTeTiposBasico_v400 import *


class evCancIECTe(ComplexType):
    """Schema XML de validação do evento cancelamento do insucesso de entrega eletrônico do CT-e 
110191"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    nProtIE: Annotated[TProt, Element] = None

