# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCCeCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v400 import *


class evCCeCTe(ComplexType):
    """Schema XML de validação do evento carta de correção 
110110"""
    descEvento: Annotated[str, Element] = None

    class _infCorrecao(ComplexType):
        """Grupo de Informações de Correção"""
        grupoAlterado: Annotated[str, Element] = None
        campoAlterado: Annotated[str, Element] = None
        valorAlterado: Annotated[str, Element] = None
        nroItemAlterado: Annotated[str, Element] = None

    infCorrecao: Annotated[ElementList[_infCorrecao], Element] = None
    xCondUso: Annotated[str, Element] = None


