# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCECTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoCTeTiposBasico_v300 import *


class evCECTe(ComplexType):
    """Schema XML de validação do evento comprovante de entrega eletrônico do CT-e 
110180"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    dhEntrega: Annotated[TDateTimeUTC, Element] = None
    nDoc: Annotated[str, Element] = None
    xNome: Annotated[str, Element] = None
    latitude: Annotated[TLatitude, Element] = None
    longitude: Annotated[TLongitude, Element] = None
    hashEntrega: Annotated[base64Binary, Element] = None
    dhHashEntrega: Annotated[TDateTimeUTC, Element] = None

    class _infEntrega(ComplexType):
        """Grupo de informações das NF-e que foram entregues ao Destinatário
Informar o grupo apenas para CT-e com tipo de serviço Normal"""
        chNFe: Annotated[TChNFe, Element] = None

    infEntrega: Annotated[ElementList[_infEntrega], Element] = None


