# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: eventoCTeTiposBasico_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .evPrestDesacordo_v200 import *
from .tiposGeralCTe_v200 import *


class TVerEvento(str):
    """Tipo Versão do Evento"""
    pass


class TEvento(ComplexType):
    """Tipo Evento"""
    versao: Annotated[TVerEvento, Attribute] = None

    class _infEvento(ComplexType):
        Id: Annotated[str, Attribute(pattern=r'ID[0-9]{52}')] = None
        cOrgao: Annotated[TCOrgaoIBGE, Element] = None
        tpAmb: Annotated[TAmb, Element] = None
        CNPJ: Annotated[TCnpj, Element] = None
        chCTe: Annotated[TChNFe, Element] = None
        dhEvento: Annotated[str, Element] = None
        tpEvento: Annotated[str, Element] = None
        nSeqEvento: Annotated[str, Element] = None

        class _detEvento(ComplexType):
            """Detalhamento do evento específico"""
            versaoEvento: Annotated[str, Attribute(pattern=r'2\.(0[0-9]|[1-9][0-9])')] = None
            evPrestDesacordo: Annotated[evPrestDesacordo, Element] = None

        detEvento: Annotated[_detEvento, Element] = None

    infEvento: Annotated[_infEvento, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TRetEvento(ComplexType):
    """Tipo retorno do Evento"""
    versao: Annotated[TVerEvento, Attribute] = None

    class _infEvento(ComplexType):
        Id: Annotated[str, Attribute(pattern=r'ID[0-9]{15}')] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        cOrgao: Annotated[TCOrgaoIBGE, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[TMotivo, Element] = None
        chCTe: Annotated[TChNFe, Element] = None
        tpEvento: Annotated[str, Element] = None
        xEvento: Annotated[str, Element] = None
        nSeqEvento: Annotated[str, Element] = None
        dhRegEvento: Annotated[str, Element] = None
        nProt: Annotated[TProt, Element] = None

    infEvento: Annotated[_infEvento, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TProcEvento(ComplexType):
    """Tipo procEvento"""
    versao: Annotated[TVerEvento, Attribute] = None
    eventoCTe: Annotated[TEvento, Element] = None
    retEventoCTe: Annotated[TRetEvento, Element] = None


class TModTransp(str):
    """ Tipo Modal transporte"""
    pass


class TNSU(str):
    """ Tipo número sequencial único do AN"""
    pass


class TPlaca(str):
    """Tipo Placa """
    pass


