# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: eventoCTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v300 import *


class eventoCTe(TEvento):
    """Schema XML de validação do Pedido de Registro de Evento do CT-e"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


