# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evEPECCTe_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoCTeTiposBasico_v200 import *


class evEPECCTe(ComplexType):
    """Schema XML de validação do evento de emissão prévia de emissão em contingência 
110113"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"
    descEvento: Annotated[str, Element] = None
    xJust: Annotated[TJust, Element] = None
    vICMS: Annotated[TDec_1302, Element] = None
    vTPrest: Annotated[TDec_1302, Element] = None
    vCarga: Annotated[TDec_1302, Element] = None

    class _toma04(ComplexType):
        """Indicador do \"papel\" do tomador do serviço no CT-e"""
        toma: Annotated[str, Element] = None
        UF: Annotated[TUf, Element] = None
        CNPJ: Annotated[TCnpjOpc, Element] = None
        CPF: Annotated[TCpf, Element] = None
        CNPJ_CPF = Choice("CNPJ", "CPF")
        IE: Annotated[TIeDest, Element] = None

    toma04: Annotated[_toma04, Element] = None
    modal: Annotated[TModTransp, Element] = None
    UFIni: Annotated[TUf, Element] = None
    UFFim: Annotated[TUf, Element] = None


