# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evRegMultimodal_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import Annotated

from brasil.dfe.xsd import ComplexType, Element


class evRegMultimodal(ComplexType):
    """Schema XML de validação do evento Registro Multimodal 110160"""
    descEvento: Annotated[str, Element] = None
    xRegistro: Annotated[str, Element] = None
    nDoc: Annotated[str, Element] = None


