# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: inutCTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .inutCTeTiposBasico_v300 import *


class inutCTe(TInutCTe):
    """Schema XML de validação do Pedido de Inutilização de Numeração do Conhecimento de Transportes eletrônico"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


