# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: inutCTeTiposBasico_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .tiposGeralCTe_v400 import *


class TVerInutCTe(str):
    """ Tipo Versão Inutilização de numeração de CT-e"""
    pass


class TInutCTe(ComplexType):
    """Tipo Pedido de Inutilização de Numeração do Conhecimento de Transporte eletrônico"""
    versao: Annotated[TVerInutCTe, Attribute] = None

    class _infInut(ComplexType):
        """Dados do Pedido de Inutilização de Numeração do Conhecimento de Transporte eletrônico"""
        Id: Annotated[str, Attribute(pattern=r'ID[0-9]{39}')] = None
        tpAmb: Annotated[TAmb, Element] = None
        xServ: Annotated[TServ, Element] = None
        cUF: Annotated[TCodUfIBGE, Element] = None
        ano: Annotated[xs:short, Element] = None
        CNPJ: Annotated[TCnpj, Element] = None
        mod: Annotated[TModCT_Carga_OS, Element] = None
        serie: Annotated[TSerie, Element] = None
        nCTIni: Annotated[TNF, Element] = None
        nCTFin: Annotated[TNF, Element] = None
        xJust: Annotated[TJust, Element] = None

    infInut: Annotated[_infInut, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TRetInutCTe(ComplexType):
    """Tipo retorno do Pedido de Inutilização de Numeração do Conhecimento de Transporte eletrônico"""
    versao: Annotated[TVerInutCTe, Attribute] = None

    class _infInut(ComplexType):
        """Dados do Retorno do Pedido de Inutilização de Numeração do Conhecimento de Transporte eletrônico"""
        Id: Annotated[str, Attribute] = None
        tpAmb: Annotated[TAmb, Element] = None
        verAplic: Annotated[TVerAplic, Element] = None
        cStat: Annotated[TStat, Element] = None
        xMotivo: Annotated[str, Element] = None
        cUF: Annotated[TCodUfIBGE, Element] = None
        ano: Annotated[xs:short, Element] = None
        CNPJ: Annotated[TCnpj, Element] = None
        mod: Annotated[TModCT_Carga_OS, Element] = None
        serie: Annotated[TSerie, Element] = None
        nCTIni: Annotated[TNF, Element] = None
        nCTFin: Annotated[TNF, Element] = None
        dhRecbto: Annotated[TDateTimeUTC, Element] = None
        nProt: Annotated[TProt, Element] = None

    infInut: Annotated[_infInut, Element] = None
    Signature: Annotated[XmlSignature, Element] = None


class TProcInutCTe(ComplexType):
    """Tipo Pedido de inutilzação de númeração de CT-e processado"""
    versao: Annotated[TVerInutCTe, Attribute] = None
    ipTransmissor: Annotated[TIPv4, Attribute] = None
    nPortaCon: Annotated[str, Attribute(pattern=r'[0-9]{1,5}')] = None
    dhConexao: Annotated[TDateTimeUTC, Attribute] = None
    inutCTe: Annotated[TInutCTe, Element] = None
    retInutCTe: Annotated[TRetInutCTe, Element] = None


