# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: inutCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .inutCTeTiposBasico_v400 import *


class inutCTe(TInutCTe):
    """Schema XML de validação do Pedido de Inutilização de Numeração do Conhecimento de Transportes eletrônico"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


