# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procEventoCTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from brasil.dfe.xsd import ComplexType


class procEventoCTe(ComplexType):
    """Pedido de Registro de Eventos de CT-e processado"""


