# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procCTeOS_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v300 import *


class cteOSProc(ComplexType):
    """ CT-e OS processado"""
    versao: Annotated[TVerCTe, Attribute] = None
    ipTransmissor: Annotated[TIPv4, Attribute] = None
    CTeOS: Annotated[TCTeOS, Element] = None
    protCTe: Annotated[TProtCTeOS, Element] = None


