# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procGTVe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v400 import *


class GTVeProc(ComplexType):
    """ GTV-e processada"""
    versao: Annotated[TVerCTe, Attribute] = None
    ipTransmissor: Annotated[TIPv4, Attribute] = None
    nPortaCon: Annotated[str, Attribute(pattern=r'[0-9]{1,5}')] = None
    dhConexao: Annotated[TDateTimeUTC, Attribute] = None
    GTVe: Annotated[TGTVe, Element] = None
    protCTe: Annotated[TProtGTVe, Element] = None


