# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v400 import *


class cteProc(ComplexType):
    """ CT-e processado"""
    versao: Annotated[TVerCTe, Attribute] = None
    ipTransmissor: Annotated[TIPv4, Attribute] = None
    nPortaCon: Annotated[str, Attribute(pattern=r'[0-9]{1,5}')] = None
    dhConexao: Annotated[TDateTimeUTC, Attribute] = None
    CTe: Annotated[TCTe, Element] = None
    protCTe: Annotated[TProtCTe, Element] = None


