# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsSitCTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .consSitCTeTiposBasico_v300 import *


class retConsSitCTe(TRetConsSitCTe):
    """Schema XML de validação do retorno da consulta da situação atual do CT-e."""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


