# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsReciCTe_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .consReciCTeTiposBasico_v200 import *


class retConsReciCTe(TRetConsReciCTe):
    """Schema XML de validação do retorno do Pedido de  Consulta do Lote de CT-e"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


