# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v400 import *


class retCTe(TRetCTe):
    """Schema XML de validação do retorno do recibo de envio do CT-e (Modelo 57)"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


