# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsCad_v1.01.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe

from .leiauteConsultaCadastro_v101 import *


class retConsCad(TRetConsCad):
    """Schema XML de validação do retorno da consulta cadastro contribuintes"""
    _xmlns = "http://www.portalfiscal.inf.br/nfe"


