# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retCTeOS_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v400 import *


class retCTeOS(TRetCTeOS):
    """Schema XML de validação do retorno do recibo de envio do CT-e OS (Modelo 67)"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


