# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEventoCTe_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .eventoCTeTiposBasico_v200 import *


class retEventoCTe(TRetEvento):
    """Schema XML de validação do retorno Pedido de Evento do CT-e"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


