# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retGTVe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .cteTiposBasico_v400 import *


class retGTVe(TRetGTVe):
    """Schema XML de validação do retorno do recibo de envio da GTV-e (Modelo 64)"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


