# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retInutCTe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .inutCTeTiposBasico_v300 import *


class retInutCTe(ComplexType):
    """Schema XML de validação do retorno do Pedido de Inutilização de Numeração do CT-e"""


