# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retInutCTe_v2.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte

from .inutCTeTiposBasico_v200 import *


class retInutCTe(TRetInutCTe):
    """Schema XML de validação do retorno do Pedido de Inutilização de Numeração do CT-e"""
    _xmlns = "http://www.portalfiscal.inf.br/cte"


