# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: tiposDistDFe_v1.00.xsd
# xmlns: http://www.portalfiscal.inf.br/nfe
from decimal import Decimal


class TNSU(str):
    """Tipo número sequencial único"""
    pass


class TQNSU(int):
    """Tipo quantidade de NSU"""
    pass


class TFinCTe(str):
    """Tipo Finalidade da CT-e"""
    pass


class TModTransp(str):
    """ Tipo Modal transporte"""
    pass


class TVerDistDFe(str):
    """Tipo Versão dos leiautes do Web Service NFeDistribuicaoDFe"""
    pass


class TAmb(str):
    """Tipo Ambiente"""
    pass


class TCodUfIBGE(str):
    """Tipo Código da UF da tabela do IBGE"""
    pass


class TCOrgaoIBGE(str):
    """Tipo Código de orgão (UF da tabela do IBGE + 90 RFB)"""
    pass


class TCnpj(str):
    """Tipo Número do CNPJ"""
    pass


class TCpf(str):
    """Tipo Número do CPF"""
    pass


class TString(str):
    """ Tipo string genérico"""
    pass


class TVerAplic(str):
    """Tipo Versão do Aplicativo"""
    pass


class TStat(str):
    """Tipo Código da Mensagem enviada"""
    pass


class TMotivo(str):
    """Tipo Motivo"""
    pass


class TChNFe(str):
    """Tipo Chave da Nota Fiscal Eletrônica"""
    pass


class TProt(str):
    """Tipo Número do Protocolo de Status"""
    pass


class TDateTimeUTC(str):
    """Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)"""
    pass


class TIe(str):
    """Tipo Inscrição Estadual do Emitente // alterado EM 24/10/08 para aceitar ISENTO"""
    pass


class TDec_1302(Decimal):
    """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais"""
    _xs_dec = (13, 2)
    _xs_optional = False


