# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: tiposGeralCTe_v4.00.xsd
# xmlns: http://www.portalfiscal.inf.br/cte
from typing import List, Annotated, TypeAlias
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature


TDateTimeUTC: TypeAlias = Annotated[str, SimpleType, """Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)""", ]


TAmb: TypeAlias = Annotated[str, SimpleType, """Tipo Ambiente""", ]


Tano: TypeAlias = Annotated[str, SimpleType, """ Tipo ano""", ]


TCodUfIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código da UF da tabela do IBGE""", ]


TCodMunIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código do Município da tabela do IBGE""", ]


TCOrgaoIBGE: TypeAlias = Annotated[str, SimpleType, """Tipo Código de orgão (UF da tabela do IBGE + 90 SUFRAMA + 91 RFB +  94 SVC-RS + 95 SVC-SP + 96  Sinc. Chaves do RS para SVSP """, ]


TChDFe: TypeAlias = Annotated[str, SimpleType, """Tipo Chave de Documento Fiscal Eletrônico""", ]


TCnpj: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CNPJ""", ]


TFone: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Telefone""", ]


TCnpjOpc: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CNPJ Opcional""", ]


TCpf: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CPF""", ]


TCpfVar: TypeAlias = Annotated[str, SimpleType, """Tipo Número do CPF de tamanho variável (3-11)""", ]


TData: TypeAlias = Annotated[str, SimpleType, """ Tipo data AAAA-MM-DD""", ]


TDec_0302: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 5 dígitos, sendo 3 de corpo e 2 decimais""", (3, 2)]


TDec_0303: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 6 dígitos, sendo 3 de corpo e 3 decimais""", (3, 3)]


TDec_0302_0303: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 6  ou 5 dígitos, sendo 3 de corpo e 3 ou 2 decimais""", (3, 2)]


TDec_0302Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 5 dígitos, sendo 3 de corpo e 2 decimais, utilizado em tags opcionais""", (3, 2, True)]


TDec_0803: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 dígitos, sendo 8 de corpo e 3 decimais""", (8, 3)]


TDec_0803Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 11 dígitos, sendo 8 de corpo e 3 decimais utilizado em tags opcionais""", (8, 3, True)]


TDec_0804: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 dígitos, sendo 8 de corpo e 4decimais""", (8, 4)]


TDec_0804Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 12 dígitos, sendo 8 de corpo e 4 decimais, utilizado em tags opcionais""", (8, 4, True)]


TDec_0906Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 9 de corpo e 6 decimais, utilizado em tags opcionais""", (9, 6, True)]


TDec_1104: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 11 de corpo e 4 decimais""", (11, 4)]


TDec_1104Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 11 de corpo e 4 decimais, utilizado em tags opcionais""", (11, 4, True)]


TDec_1203: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 12 de corpo e 3 decimais""", (12, 3)]


TDec_1203Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 12 de corpo e 3 decimais, utilizado em tags opcionais""", (12, 3, True)]


TDec_1204: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 16 dígitos, sendo 12 de corpo e 4 decimais""", (12, 4)]


TDec_1204Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 16 dígitos, sendo 12 de corpo e 4 decimais, utilizado em tags opcionais""", (12, 4, True)]


TDec_1302: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais""", (13, 2)]


TDec_1302Opc: TypeAlias = Annotated[Decimal, SimpleType, """Tipo Decimal com 15 dígitos, sendo 13 de corpo e 2 decimais, utilizado em tags opcionais""", (13, 2, True)]


TIe: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do Emitente""", ]


TIeDest: TypeAlias = Annotated[str, SimpleType, """Tipo Inscrição Estadual do Destinatário""", ]


TString: TypeAlias = Annotated[str, SimpleType, """ Tipo string genérico""", ]


TJust: TypeAlias = Annotated[str, SimpleType, """Tipo Justificativa""", ]


TMed: TypeAlias = Annotated[str, SimpleType, """ Tipo temp médio em segundos""", ]


TModCTOS: TypeAlias = Annotated[str, SimpleType, """Tipo Modelo Documento Fiscal""", ]


TModGTVe: TypeAlias = Annotated[str, SimpleType, """Tipo Modelo Documento Fiscal""", ]


TModCT_Carga_OS: TypeAlias = Annotated[str, SimpleType, """Tipo Modelo Documento Fiscal""", ]


TModCT: TypeAlias = Annotated[str, SimpleType, """Tipo Modelo Documento Fiscal""", ]


TModNF: TypeAlias = Annotated[str, SimpleType, """Tipo Modelo Documento Fiscal - NF Remetente""", ]


TtipoUnidTransp: TypeAlias = Annotated[str, SimpleType, """Tipo da Unidade de Transporte""", ]


TtipoUnidCarga: TypeAlias = Annotated[str, SimpleType, """Tipo da Unidade de Carga""", ]


TMotivo: TypeAlias = Annotated[str, SimpleType, """Tipo Motivo""", ]


TNF: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Documento Fiscal""", ]


TProt: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Protocolo de Status""", ]


TRec: TypeAlias = Annotated[str, SimpleType, """Tipo Número do Recibo do envio de lote de NF-e""", ]


TSerie: TypeAlias = Annotated[str, SimpleType, """Tipo Série do Documento Fiscal """, ]


TServ: TypeAlias = Annotated[str, SimpleType, """Tipo Serviço solicitado""", ]


TStat: TypeAlias = Annotated[str, SimpleType, """Tipo Código da Mensagem enviada""", ]


TUf: TypeAlias = Annotated[str, SimpleType, """Tipo Sigla da UF""", ]


TUF_sem_EX: TypeAlias = Annotated[str, SimpleType, """Tipo Sigla da UF, sem Exterior""", ]


TVerAplic: TypeAlias = Annotated[str, SimpleType, """Tipo Versão do Aplicativo""", ]


TLatitude: TypeAlias = Annotated[str, SimpleType, """Coordenada geográfica Latitude""", ]


TLongitude: TypeAlias = Annotated[str, SimpleType, """Coordenada geográfica Longitude""", ]


TIPv4: TypeAlias = Annotated[str, SimpleType, """Tipo IP versão 4""", ]


TPlaca: TypeAlias = Annotated[str, SimpleType, """Tipo Placa """, ]


class TRSAKeyValueType(ComplexType):
    """Tipo que representa uma chave publica padrão RSA"""
    Modulus: Annotated[base64Binary, Element] = None
    Exponent: Annotated[base64Binary, Element] = None


