# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consReciMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .consReciMDFeTiposBasico_v300 import *


class consReciMDFe(TConsReciMDFe):
    """Schema XML de validação do Pedido de Consulta de MDF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


