# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consMDFeNaoEncTiposBasico_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposGeralMDFe_v300 import *


class TVerConsMDFeNaoEnc(str):
    """ Tipo Versão do Consulta MDF-e não encerrados - 3.00"""
    pass


class TConsMDFeNaoEnc(ComplexType):
    """Tipo Pedido de Consulta MDF-e Não Encerrados"""
    versao: Annotated[TVerConsMDFeNaoEnc, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    xServ: Annotated[TServ, Element] = None
    CNPJ: Annotated[TCnpj, Element] = None
    CPF: Annotated[TCpf, Element] = None
    CNPJ_CPF = Choice("CNPJ", "CPF")


class TRetConsMDFeNaoEnc(ComplexType):
    """Tipo Retorno de Pedido de Consulta MDF-e não Encerrados"""
    versao: Annotated[TVerConsMDFeNaoEnc, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None

    class _infMDFe(ComplexType):
        chMDFe: Annotated[TChMDFe, Element] = None
        nProt: Annotated[TProt, Element] = None

    infMDFe: Annotated[ElementList[_infMDFe], Element] = None

