# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consSitMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .consSitMDFeTiposBasico_v300 import *


class consSitMDFe(TConsSitMDFe):
    """Schema de validação XML dp Pedido de Consulta da Situação Atual do MDF-e."""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"

