# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consSitMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .consSitMDFeTiposBasico_v300 import *


class consSitMDFe(TConsSitMDFe):
    """Schema de validação XML dp Pedido de Consulta da Situação Atual do MDF-e."""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


