# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consStatServMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .consStatServTiposBasico_v300 import *


class consStatServMDFe(TConsStatServ):
    """Schema XML de validação do Pedido de Consulta do Status do Serviço MDF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


