# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consStatServTiposBasico_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .tiposGeralMDFe_v300 import *


class TVerConsStat(str):
    """ Tipo Versão do Consulta do Status do Serviço MDFe"""
    pass


class TConsStatServ(ComplexType):
    """Tipo Pedido de Consulta do Status do Serviço MDFe"""
    versao: Annotated[TVerConsStat, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    xServ: Annotated[TServ, Element] = None


class TRetConsStatServ(ComplexType):
    """Tipo Resultado da Consulta do Status do Serviço MDFe"""
    versao: Annotated[TVerConsStat, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    dhRecbto: Annotated[TDateTimeUTC, Element] = None
    tMed: Annotated[int, Element] = None
    dhRetorno: Annotated[TDateTimeUTC, Element] = None
    xObs: Annotated[str, Element] = None


