# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: consSitMDFeTiposBasico_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposGeralMDFe_v300 import *
from .procMDFe_v300 import *


class TVerConsSitMDFe(str):
    """ Tipo Versão do Consulta situação de MDF-e - 1.00"""
    pass


class TConsSitMDFe(ComplexType):
    """Tipo Pedido de Consulta da Situação Atual do MDF-e"""
    versao: Annotated[TVerConsSitMDFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    xServ: Annotated[TServ, Element] = None
    chMDFe: Annotated[TChNFe, Element] = None


class TRetConsSitMDFe(ComplexType):
    """Tipo Retorno de Pedido de Consulta da Situação Atual do MDF-e"""
    versao: Annotated[TVerConsSitMDFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    cUF: Annotated[TCodUfIBGE, Element] = None
    protMDFe: Annotated[TProtMDFe, Element] = None

    class _procEventoMDFe(ComplexType):
        """Retornar procEventoMDFe da versão correspondente do evento MDF-e autorizado"""
        versao: Annotated[str, Attribute(enumeration=['1.00', '3.00'])] = None

    procEventoMDFe: Annotated[ElementList[_procEventoMDFe], Element] = None

    class _procInfraSA(ComplexType):
        """Grupo de informações do compartilhamento do MDFe com InfraSA para geração do DTe"""
        nProtDTe: Annotated[TProt, Element] = None
        dhProt: Annotated[TDateTimeUTC, Element] = None

    procInfraSA: Annotated[_procInfraSA, Element] = None


