# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: distMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .leiauteDistMDFe_v300 import *


class distMDFe(TDistDFe):
    """solicitação de distribuição de MDF-e para o Ambiente Autorizador"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"

