# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: distMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .leiauteDistMDFe_v300 import *


class distMDFe(TDistDFe):
    """solicitação de distribuição de MDF-e para o Ambiente Autorizador"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


