# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: enviMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .mdfeTiposBasico_v300 import *


class enviMDFe(TEnviMDFe):
    """Schema XML de validação do Envio de Lote MDF-e para concessão de autorização"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


