# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evCancMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .eventoMDFeTiposBasico_v300 import *


class evCancMDFe(ComplexType):
    """Schema XML de validação do evento do cancelamento 
110111"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    xJust: Annotated[TJust, Element] = None


