# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evConfirmaServMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoMDFeTiposBasico_v300 import *


class evConfirmaServMDFe(ComplexType):
    """Schema XML de validação do evento de confirmação do serviço de transporte 110117"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None


