# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: eventoMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .eventoMDFeTiposBasico_v300 import *


class eventoMDFe(TEvento):
    """Schema XML de validação do Pedido de Registro de Evento do MDF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


