# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evEncMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoMDFeTiposBasico_v300 import *


class evEncMDFe(ComplexType):
    """Schema XML de validação do evento do encerramento 
110112"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    dtEnc: Annotated[TData, Element] = None
    cUF: Annotated[TCodUfIBGE_EX, Element] = None
    cMun: Annotated[TCodMunIBGE, Element] = None
    indEncPorTerceiro: Annotated[str, Element] = None


