# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evInclusaoDFeMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoMDFeTiposBasico_v300 import *


class evIncDFeMDFe(ComplexType):
    """Schema XML de validação do evento de inclusão de DFe 
110115"""
    descEvento: Annotated[str, Element] = None
    nProt: Annotated[TProt, Element] = None
    cMunCarrega: Annotated[TCodMunIBGE, Element] = None
    xMunCarrega: Annotated[str, Element] = None

    class _infDoc(ComplexType):
        """Informações dos Documentos fiscais vinculados ao manifesto"""
        cMunDescarga: Annotated[TCodMunIBGE, Element] = None
        xMunDescarga: Annotated[str, Element] = None
        chNFe: Annotated[TChNFe, Element] = None

    infDoc: Annotated[ElementList[_infDoc], Element] = None


