# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: evIncCondutorMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .eventoMDFeTiposBasico_v300 import *


class evIncCondutorMDFe(ComplexType):
    """Schema XML de validação do evento de inclusao de condutor 110114"""
    descEvento: Annotated[str, Element] = None

    class _condutor(ComplexType):
        """Informações do(s) Condutor(s) do veículo"""
        xNome: Annotated[str, Element] = None
        CPF: Annotated[TCpf, Element] = None

    condutor: Annotated[_condutor, Element] = None

