# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: leiauteDistMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .tiposGeralMDFe_v300 import *


class TVerDFe(str):
    """ Tipo Versão"""
    pass


class TDistDFe(ComplexType):
    """Schema XML de validação da área de dados da mensagem da solicitação de distribuição de DF-e"""
    versao: Annotated[TVerDFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    indDFe: Annotated[int, Element] = None
    indCompRet: Annotated[int, Element] = None
    ultNSU: Annotated[TNSU, Element] = None


class TLoteDistDFe(ComplexType):
    """Schema XML de validação da área de dados descompactada"""
    versao: Annotated[TVerDFe, Attribute] = None

    class _proc(ComplexType):
        """informação do proc"""
        schema: Annotated[str, Attribute] = None
        NSU: Annotated[TNSU, Attribute] = None
        ipTransmissor: Annotated[TIPv4, Attribute] = None

    proc: Annotated[ElementList[_proc], Element] = None


class TRetDistDFe(ComplexType):
    """Schema XML de validação do lote de retorno de documentos ficais eletronicos"""
    versao: Annotated[TVerDFe, Attribute] = None
    tpAmb: Annotated[TAmb, Element] = None
    verAplic: Annotated[TVerAplic, Element] = None
    cStat: Annotated[TStat, Element] = None
    xMotivo: Annotated[TMotivo, Element] = None
    ultNSU: Annotated[TNSU, Element] = None
    loteDistMDFeComp: Annotated[base64Binary, Element] = None
    loteDistMDFe: Annotated[TLoteDistDFe, Element] = None
    loteDistMDFeComp_loteDistMDFe = Choice("loteDistMDFeComp", "loteDistMDFe")


