# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: mdfeModalAquaviario_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .mdfeTiposBasico_v300 import *


class aquav(ComplexType):
    """Informações do modal Aquaviário"""
    irin: Annotated[str, Element] = None
    tpEmb: Annotated[str, Element] = None
    cEmbar: Annotated[str, Element] = None
    xEmbar: Annotated[str, Element] = None
    nViag: Annotated[str, Element] = None
    cPrtEmb: Annotated[str, Element] = None
    cPrtDest: Annotated[str, Element] = None
    prtTrans: Annotated[str, Element] = None
    tpNav: Annotated[str, Element] = None

    class _infTermCarreg(ComplexType):
        """Grupo de informações dos terminais de carregamento."""
        cTermCarreg: Annotated[str, Element] = None
        xTermCarreg: Annotated[str, Element] = None

    infTermCarreg: Annotated[ElementList[_infTermCarreg], Element] = None

    class _infTermDescarreg(ComplexType):
        """Grupo de informações dos terminais de descarregamento."""
        cTermDescarreg: Annotated[str, Element] = None
        xTermDescarreg: Annotated[str, Element] = None

    infTermDescarreg: Annotated[ElementList[_infTermDescarreg], Element] = None

    class _infEmbComb(ComplexType):
        """Informações das Embarcações do Comboio"""
        cEmbComb: Annotated[str, Element] = None
        xBalsa: Annotated[str, Element] = None

    infEmbComb: Annotated[ElementList[_infEmbComb], Element] = None

    class _infUnidCargaVazia(ComplexType):
        """Informações das Undades de Carga vazias"""
        idUnidCargaVazia: Annotated[TContainer, Element] = None
        tpUnidCargaVazia: Annotated[str, Element] = None

    infUnidCargaVazia: Annotated[ElementList[_infUnidCargaVazia], Element] = None

    class _infUnidTranspVazia(ComplexType):
        """Informações das Undades de Transporte vazias"""
        idUnidTranspVazia: Annotated[TContainer, Element] = None
        tpUnidTranspVazia: Annotated[str, Element] = None

    infUnidTranspVazia: Annotated[ElementList[_infUnidTranspVazia], Element] = None


