# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: mdfe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .mdfeTiposBasico_v300 import *


class MDFe(TMDFe):
    """Manisfesto Eletrônico de Documentos Fiscais"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


