# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: mdfeModalAereo_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .tiposGeralMDFe_v300 import *


class aereo(ComplexType):
    """Informações do modal Aéreo"""
    nac: Annotated[str, Element] = None
    matr: Annotated[str, Element] = None
    nVoo: Annotated[str, Element] = None
    cAerEmb: Annotated[str, Element] = None
    cAerDes: Annotated[str, Element] = None
    dVoo: Annotated[TData, Element] = None


