# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .mdfeTiposBasico_v300 import *


class mdfeProc(ComplexType):
    """ MDF-e processado"""
    versao: Annotated[TVerMDe, Attribute] = None
    ipTransmissor: Annotated[TIPv4, Attribute] = None
    nPortaCon: Annotated[str, Attribute(pattern=r'[0-9]{1,5}')] = None
    dhConexao: Annotated[TDateTimeUTC, Attribute] = None
    MDFe: Annotated[TMDFe, Element] = None
    protMDFe: Annotated[TProtMDFe, Element] = None


