# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: procEventoMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .eventoMDFeTiposBasico_v300 import *


class procEventoMDFe(TProcEvento):
    """Pedido de Registro de Evento de MDF-e processado"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


