# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsSitMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .consSitMDFeTiposBasico_v300 import *


class retConsSitMDFe(TRetConsSitMDFe):
    """Schema XML de validação do retorno da consulta da situação atual do MDF-e."""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


