# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retConsReciMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature
from .consReciMDFeTiposBasico_v300 import *


class retConsReciMDFe(TRetConsReciMDFe):
    """Schema XML de validação do retorno do Pedido de Consulta do MDF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


