# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retDistMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .leiauteDistMDFe_v300 import *


class retDistMDFe(TRetDistDFe):
    """Retorno de pedido de distribuição de MDF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


