# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: retEventoMDFe_v3.00.xsd
# xmlns: http://www.portalfiscal.inf.br/mdfe

from .eventoMDFeTiposBasico_v300 import *


class retEventoMDFe(TRetEvento):
    """Schema XML de validação do retorno Pedido de Cancelamento do MDF-e"""
    _xmlns = "http://www.portalfiscal.inf.br/mdfe"


