# Generated by xsd2py.py
# DO NOT CHANGE THIS FILE (use compile override instead)
# xsd: xmldsig-core-schema_v1.01.xsd
# xmlns: http://www.w3.org/2000/09/xmldsig#
from typing import List, Annotated
from datetime import date, datetime
from decimal import Decimal

from brasil.dfe.xsd import Choice, SimpleType, ComplexType, Attribute, Element, TString, Restriction, ID, base64Binary, anyURI, string, dateTime, TXML, ElementList, XmlSignature


class Signature(TXML):
    _xmlns = "http://www.w3.org/2000/09/xmldsig#"


class SignatureType(ComplexType):
    Id: Annotated[ID, Attribute] = None
    SignedInfo: Annotated[TXML, Element] = None
    SignatureValue: Annotated[TXML, Element] = None
    KeyInfo: Annotated[TXML, Element] = None


class SignatureValueType(ComplexType):
    _simple_content = base64Binary


class SignedInfoType(ComplexType):
    Id: Annotated[ID, Attribute] = None

    class _CanonicalizationMethod(ComplexType):
        Algorithm: Annotated[anyURI, Attribute] = None

    CanonicalizationMethod: Annotated[_CanonicalizationMethod, Element] = None

    class _SignatureMethod(ComplexType):
        Algorithm: Annotated[anyURI, Attribute] = None

    SignatureMethod: Annotated[_SignatureMethod, Element] = None
    Reference: Annotated[TXML, Element] = None


class ReferenceType(ComplexType):
    Id: Annotated[ID, Attribute] = None
    URI: Annotated[anyURI, Attribute(min_length=2)] = None
    Type: Annotated[anyURI, Attribute] = None
    Transforms: Annotated[TXML, Element] = None

    class _DigestMethod(ComplexType):
        Algorithm: Annotated[anyURI, Attribute] = None

    DigestMethod: Annotated[_DigestMethod, Element] = None
    DigestValue: Annotated[TXML, Element] = None


class TransformsType(ComplexType):
    Transform: Annotated[ElementList[TXML], Element] = None


class TransformType(ComplexType):
    Algorithm: Annotated[ds:TTransformURI, Attribute] = None
    XPath: Annotated[ElementList[string], Element] = None


class KeyInfoType(ComplexType):
    Id: Annotated[ID, Attribute] = None
    X509Data: Annotated[TXML, Element] = None


class X509DataType(ComplexType):
    X509Certificate: Annotated[base64Binary, Element] = None


class DigestValueType(base64Binary):
    pass


class TTransformURI(anyURI):
    pass


